/* Generated by compaheuiler — https://github.com/youknowone/aheui-rust
 * This code includes runtime components licensed under AGPL-3.0-or-later.
 * Distributing binaries compiled from this code requires compliance with the AGPL.
 */
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include <limits.h>

#define STORAGE_COUNT 28
#define MAX_STACK 65536
#define QUEUE_CAP 65536
#define PORT_CAP 65536

static inline int64_t wrapping_div(int64_t a, int64_t b) {
    if (a == INT64_MIN && b == -1) return INT64_MIN;
    int64_t q = a / b, r = a % b;
    if (r != 0 && (r < 0) != (b < 0)) q -= 1;
    return q;
}
static inline int64_t wrapping_rem(int64_t a, int64_t b) {
    if (a == INT64_MIN && b == -1) return 0;
    int64_t q = a / b, r = a % b;
    (void)q;
    if (r != 0 && (r < 0) != (b < 0)) r += b;
    return r;
}

typedef struct {
    int64_t queue[QUEUE_CAP];
    size_t q_head;
    size_t q_len;
    int64_t port[PORT_CAP];
    size_t p_len;
    int64_t port_last;
} SpecialStorage;

static inline void sp_init(SpecialStorage* s) {
    s->q_head = 0; s->q_len = 0; s->p_len = 0; s->port_last = 0;
}

static void sp_overflow(void) {
    fputs("compaheuiler: special storage capacity exceeded\n", stderr);
    exit(1);
}

static inline void sp_push(SpecialStorage* s, size_t sel, int64_t v) {
    if (sel == 21) {
        if (s->q_len >= QUEUE_CAP) sp_overflow();
        s->queue[(s->q_head + s->q_len) % QUEUE_CAP] = v;
        s->q_len++;
    } else {
        if (s->p_len >= PORT_CAP) sp_overflow();
        s->port_last = v;
        s->port[s->p_len++] = v;
    }
}

static inline int64_t sp_pop(SpecialStorage* s, size_t sel) {
    if (sel == 21) {
        if (s->q_len == 0) return 0;
        int64_t v = s->queue[s->q_head];
        s->q_head = (s->q_head + 1) % QUEUE_CAP;
        s->q_len--;
        return v;
    } else {
        if (s->p_len == 0) return 0;
        return s->port[--s->p_len];
    }
}

static inline size_t sp_depth(SpecialStorage* s, size_t sel) {
    return (sel == 21) ? s->q_len : s->p_len;
}

static inline void sp_dup(SpecialStorage* s, size_t sel) {
    if (sel == 21) {
        if (s->q_len > 0) {
            if (s->q_len >= QUEUE_CAP) sp_overflow();
            int64_t v = s->queue[s->q_head];
            /* push_front: move head back */
            s->q_head = (s->q_head + QUEUE_CAP - 1) % QUEUE_CAP;
            s->queue[s->q_head] = v;
            s->q_len++;
        }
    } else {
        if (s->p_len >= PORT_CAP) sp_overflow();
        s->port[s->p_len] = s->port_last;
        s->p_len++;
    }
}

/* Duplicate the queue front onto the back: one rotation step, which is what a
   duplicate immediately followed by a move to the same queue amounts to. */
static inline void sp_dup_back(SpecialStorage* s) {
    if (s->q_len > 0) {
        if (s->q_len >= QUEUE_CAP) sp_overflow();
        s->queue[(s->q_head + s->q_len) % QUEUE_CAP] = s->queue[s->q_head];
        s->q_len++;
    }
}

static inline void sp_swap(SpecialStorage* s, size_t sel) {
    if (sel == 21 && s->q_len >= 2) {
        size_t i0 = s->q_head;
        size_t i1 = (s->q_head + 1) % QUEUE_CAP;
        int64_t tmp = s->queue[i0];
        s->queue[i0] = s->queue[i1];
        s->queue[i1] = tmp;
    } else if (sel == 27 && s->p_len >= 2) {
        int64_t tmp = s->port[s->p_len - 1];
        s->port[s->p_len - 1] = s->port[s->p_len - 2];
        s->port[s->p_len - 2] = tmp;
    }
}

static inline void sp_scan_to_zero(SpecialStorage* s) {
    /* rotate_left(pos+1): every element up to and including the zero moves to
       the back, in order, and the one after it becomes the front. Advancing
       q_head alone is not that rotation -- the ring keeps its length, so the
       slots it pulls in at the back are the ones past the old back, not the
       elements just scanned. */
    for (size_t i = 0; i < s->q_len; i++) {
        int64_t v = s->queue[s->q_head];
        s->q_head = (s->q_head + 1) % QUEUE_CAP;
        s->queue[(s->q_head + s->q_len - 1) % QUEUE_CAP] = v;
        if (v == 0) return;
    }
}

static char _outbuf[16384];
static size_t _outpos = 0;
static inline void _flush(void) { if (_outpos > 0) { fwrite(_outbuf, 1, _outpos, stdout); _outpos = 0; } }
static inline void _emit(char c) { _outbuf[_outpos++] = c; if (_outpos >= 16384) _flush(); }

static inline void write_num(int64_t n) {
    if (n < 0) {
        _emit('-');
        uint64_t u = (uint64_t)(-(n + 1)) + 1;
        char buf[20]; int i = 20;
        do { buf[--i] = '0' + (u % 10); u /= 10; } while (u > 0);
        for (; i < 20; i++) _emit(buf[i]);
    } else {
        uint64_t u = (uint64_t)n;
        char buf[20]; int i = 20;
        do { buf[--i] = '0' + (u % 10); u /= 10; } while (u > 0);
        for (; i < 20; i++) _emit(buf[i]);
    }
}

static inline void write_char(int64_t v) {
    uint32_t c = (uint32_t)v;
    if (c <= 0x7F) { _emit((char)c); }
    else if (c <= 0x7FF) { _emit(0xC0 | (c >> 6)); _emit(0x80 | (c & 0x3F)); }
    else if (c <= 0xFFFF) { _emit(0xE0 | (c >> 12)); _emit(0x80 | ((c >> 6) & 0x3F)); _emit(0x80 | (c & 0x3F)); }
    else if (c <= 0x10FFFF) { _emit(0xF0 | (c >> 18)); _emit(0x80 | ((c >> 12) & 0x3F)); _emit(0x80 | ((c >> 6) & 0x3F)); _emit(0x80 | (c & 0x3F)); }
}

static inline int64_t read_num(void) {
    char buf[64];
    if (fgets(buf, sizeof(buf), stdin) == NULL) return 0;
    return (int64_t)atoll(buf);
}

static inline int64_t read_char_(void) {
    int b = getchar();
    if (b == EOF) return -1;
    if (b < 0x80) return (int64_t)b;
    int n; int32_t val;
    if ((b >> 5) == 6) { n = 1; val = b & 0x1F; }
    else if ((b >> 4) == 14) { n = 2; val = b & 0x0F; }
    else if ((b >> 3) == 30) { n = 3; val = b & 0x07; }
    else return -1;
    for (int i = 0; i < n; i++) {
        int c = getchar();
        if (c == EOF) return -1;
        val = (val << 6) | (c & 0x3F);
    }
    return (int64_t)val;
}

