/* Generated by compaheuiler — https://github.com/youknowone/aheui-rust
 * This code includes runtime components licensed under AGPL-3.0-or-later.
 *
 * Dual integer representation:
 *   mode 0: every word is an ordinary signed int64_t
 *   mode 1: odd words are signed 62-bit immediates, even words are Rust BigInt*
 * The first overflowing add/sub/mul converts every live storage exactly once.
 * Actual bigint work is provided by c_bigint_bridge.rs and linked by Rust.
 */
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include <limits.h>
#include <errno.h>

#define STORAGE_COUNT 28
#define MAX_STACK 65536
#define QUEUE_CAP 65536
#define PORT_CAP 65536
#define SMALL_MIN (-(INT64_C(1) << 62))
#define SMALL_MAX ((INT64_C(1) << 62) - 1)

#if defined(__GNUC__) || defined(__clang__)
#define CBIG_INLINE static inline __attribute__((always_inline))
#define CBIG_LIKELY(v) __builtin_expect(!!(v), 1)
#else
#define CBIG_INLINE static inline
#define CBIG_LIKELY(v) (v)
#endif

/* Rust BigInt bridge. Values use the same odd-immediate/even-pointer ABI. */
extern int64_t cbig_from_i64(int64_t value);
extern int64_t cbig_add(int64_t a, int64_t b);
extern int64_t cbig_sub(int64_t a, int64_t b);
extern int64_t cbig_mul(int64_t a, int64_t b);
extern int64_t cbig_div(int64_t a, int64_t b);
extern int64_t cbig_rem(int64_t a, int64_t b);
extern int cbig_ge(int64_t a, int64_t b);
extern int64_t cbig_to_i64(int64_t value);
extern void cbig_write_num(int64_t value, void (*emit)(uint8_t));

CBIG_INLINE int try_add(int64_t a, int64_t b, int64_t *r);
CBIG_INLINE int try_sub(int64_t a, int64_t b, int64_t *r);
CBIG_INLINE int try_mul(int64_t a, int64_t b, int64_t *r);

static int64_t tag_small(int64_t v) { return (int64_t)(((uint64_t)v << 1) | 1); }
static int64_t int_lit(int64_t v, int bm) { return bm ? tag_small(v) : v; }
static int64_t promote_val(int64_t v) {
    return v >= SMALL_MIN && v <= SMALL_MAX ? tag_small(v) : cbig_from_i64(v);
}
static int int_is_zero(int64_t v, int bm) { return bm ? v == 1 : v == 0; }
static int64_t int_to_i64(int64_t v, int bm) {
    if (!bm) return v;
    return (v & 1) ? v >> 1 : cbig_to_i64(v);
}
static int int_ge(int64_t a, int64_t b, int bm) {
    if (!bm) return a >= b;
    return (a & b & 1) != 0 ? a >= b : cbig_ge(a, b);
}
CBIG_INLINE int64_t tag_add(int64_t a, int64_t b) {
    if ((a & b & 1) != 0) { int64_t r; if (try_add(a >> 1, b >> 1, &r) && r >= SMALL_MIN && r <= SMALL_MAX) return tag_small(r); }
    return cbig_add(a, b);
}
CBIG_INLINE int64_t tag_sub(int64_t a, int64_t b) {
    if ((a & b & 1) != 0) { int64_t r; if (try_sub(a >> 1, b >> 1, &r) && r >= SMALL_MIN && r <= SMALL_MAX) return tag_small(r); }
    return cbig_sub(a, b);
}
CBIG_INLINE int64_t tag_mul(int64_t a, int64_t b) {
    if ((a & b & 1) != 0) { int64_t r; if (try_mul(a >> 1, b >> 1, &r) && r >= SMALL_MIN && r <= SMALL_MAX) return tag_small(r); }
    return cbig_mul(a, b);
}

typedef struct {
    int64_t queue[QUEUE_CAP]; size_t q_head, q_len;
    int64_t port[PORT_CAP]; size_t p_len; int64_t port_last;
    int big_mode;
} SpecialStorage;
static void sp_init(SpecialStorage *s) { s->q_head=0; s->q_len=0; s->p_len=0; s->port_last=0; s->big_mode=0; }
static void sp_overflow(void) { fputs("compaheuiler: special storage capacity exceeded\n", stderr); exit(1); }
static void sp_push(SpecialStorage *s, size_t sel, int64_t v) { if (sel==21) { if(s->q_len>=QUEUE_CAP)sp_overflow(); s->queue[(s->q_head+s->q_len)%QUEUE_CAP]=v; s->q_len++; } else { if(s->p_len>=PORT_CAP)sp_overflow(); s->port_last=v; s->port[s->p_len++]=v; } }
static int64_t sp_pop(SpecialStorage *s, size_t sel) { if (sel==21) { if (!s->q_len) return s->big_mode ? 1 : 0; int64_t v=s->queue[s->q_head]; s->q_head=(s->q_head+1)%QUEUE_CAP; s->q_len--; return v; } if (!s->p_len) return s->big_mode ? 1 : 0; return s->port[--s->p_len]; }
static size_t sp_depth(SpecialStorage *s, size_t sel) { return sel==21 ? s->q_len : s->p_len; }
static void sp_dup(SpecialStorage *s, size_t sel) { if (sel==21) { if (s->q_len) { if(s->q_len>=QUEUE_CAP)sp_overflow(); int64_t v=s->queue[s->q_head]; s->q_head=(s->q_head+QUEUE_CAP-1)%QUEUE_CAP; s->queue[s->q_head]=v; s->q_len++; } } else { if(s->p_len>=PORT_CAP)sp_overflow(); s->port[s->p_len++]=s->port_last; } }
static void sp_swap(SpecialStorage *s, size_t sel) { if (sel==21 && s->q_len>=2) { size_t a=s->q_head,b=(a+1)%QUEUE_CAP; int64_t t=s->queue[a];s->queue[a]=s->queue[b];s->queue[b]=t; } else if (sel==27 && s->p_len>=2) { int64_t t=s->port[s->p_len-1];s->port[s->p_len-1]=s->port[s->p_len-2];s->port[s->p_len-2]=t; } }
static void sp_scan_to_zero(SpecialStorage *s) { int64_t z=s->big_mode?1:0; for(size_t i=0;i<s->q_len;i++){size_t k=(s->q_head+i)%QUEUE_CAP;if(s->queue[k]==z){s->q_head=(s->q_head+i+1)%QUEUE_CAP;return;}} }
static void sp_promote(SpecialStorage *s) { for(size_t i=0;i<s->q_len;i++){size_t k=(s->q_head+i)%QUEUE_CAP;s->queue[k]=promote_val(s->queue[k]);} for(size_t i=0;i<s->p_len;i++)s->port[i]=promote_val(s->port[i]); s->port_last=promote_val(s->port_last);s->big_mode=1; }
static void do_promote(int *bm, int64_t **bases, int64_t **tops, SpecialStorage *sp) { *bm=1; for(size_t s=0;s<STORAGE_COUNT;s++) if(tops[s]) for(int64_t*p=bases[s];p<tops[s];p++)*p=promote_val(*p); sp_promote(sp); }

CBIG_INLINE int try_add(int64_t a,int64_t b,int64_t*r){
#if defined(__GNUC__) || defined(__clang__)
return !__builtin_add_overflow(a,b,r);
#else
if((b>0&&a>INT64_MAX-b)||(b<0&&a<INT64_MIN-b))return 0;*r=a+b;return 1;
#endif
}
CBIG_INLINE int try_sub(int64_t a,int64_t b,int64_t*r){
#if defined(__GNUC__) || defined(__clang__)
return !__builtin_sub_overflow(a,b,r);
#else
if((b<0&&a>INT64_MAX+b)||(b>0&&a<INT64_MIN+b))return 0;*r=a-b;return 1;
#endif
}
CBIG_INLINE int try_mul(int64_t a,int64_t b,int64_t*r){
#if defined(__GNUC__) || defined(__clang__)
return !__builtin_mul_overflow(a,b,r);
#else
if(!a||!b){*r=0;return 1;}if((a==-1&&b==INT64_MIN)||(b==-1&&a==INT64_MIN))return 0;if(a>0?(b>0?a>INT64_MAX/b:b<INT64_MIN/a):(b>0?a<INT64_MIN/b:a!=0&&b<INT64_MAX/a))return 0;*r=a*b;return 1;
#endif
}
CBIG_INLINE int64_t dual_add(int64_t a,int64_t b,int*bm,int64_t**bases,int64_t**tops,SpecialStorage*sp){if(CBIG_LIKELY(!*bm)){int64_t r;if(CBIG_LIKELY(try_add(a,b,&r)))return r;do_promote(bm,bases,tops,sp);return tag_add(promote_val(a),promote_val(b));}return tag_add(a,b);}
CBIG_INLINE int64_t dual_sub(int64_t a,int64_t b,int*bm,int64_t**bases,int64_t**tops,SpecialStorage*sp){if(CBIG_LIKELY(!*bm)){int64_t r;if(CBIG_LIKELY(try_sub(a,b,&r)))return r;do_promote(bm,bases,tops,sp);return tag_sub(promote_val(a),promote_val(b));}return tag_sub(a,b);}
CBIG_INLINE int64_t dual_mul(int64_t a,int64_t b,int*bm,int64_t**bases,int64_t**tops,SpecialStorage*sp){if(CBIG_LIKELY(!*bm)){int64_t r;if(CBIG_LIKELY(try_mul(a,b,&r)))return r;do_promote(bm,bases,tops,sp);return tag_mul(promote_val(a),promote_val(b));}return tag_mul(a,b);}
static int64_t wrapping_div(int64_t a,int64_t b){if(a==INT64_MIN&&b==-1)return INT64_MIN;int64_t q=a/b,r=a%b;if(r!=0&&(r<0)!=(b<0))q-=1;return q;}
static int64_t wrapping_rem(int64_t a,int64_t b){if(a==INT64_MIN&&b==-1)return 0;int64_t r=a%b;if(r!=0&&(r<0)!=(b<0))r+=b;return r;}
static int64_t int_div(int64_t a,int64_t b,int bm){if(!bm)return b?wrapping_div(a,b):0;if(b==1)return 1;if((a&b&1)!=0)return tag_small(wrapping_div(a>>1,b>>1));return cbig_div(a,b);}
static int64_t int_rem(int64_t a,int64_t b,int bm){if(!bm)return b?wrapping_rem(a,b):0;if(b==1)return 1;if((a&b&1)!=0)return tag_small(wrapping_rem(a>>1,b>>1));return cbig_rem(a,b);}

static char _outbuf[16384]; static size_t _outpos=0;
static void _flush(void){if(_outpos){fwrite(_outbuf,1,_outpos,stdout);_outpos=0;}}
static void _emit(char c){_outbuf[_outpos++]=c;if(_outpos>=sizeof(_outbuf))_flush();}
static void _emit_u8(uint8_t c){_emit((char)c);}
static void write_i64(int64_t n){uint64_t u;if(n<0){_emit('-');u=(uint64_t)(-(n+1))+1;}else u=n;char b[20];int i=20;do{b[--i]='0'+u%10;u/=10;}while(u);while(i<20)_emit(b[i++]);}
static void write_num(int64_t v,int bm){if(!bm){write_i64(v);return;}if(v&1){write_i64(v>>1);return;}cbig_write_num(v,_emit_u8);}
static void write_char(int64_t v,int bm){uint32_t c=(uint32_t)int_to_i64(v,bm);if(c<=0x7f)_emit((char)c);else if(c<=0x7ff){_emit(0xc0|(c>>6));_emit(0x80|(c&63));}else if(c<=0xffff){_emit(0xe0|(c>>12));_emit(0x80|((c>>6)&63));_emit(0x80|(c&63));}else if(c<=0x10ffff){_emit(0xf0|(c>>18));_emit(0x80|((c>>12)&63));_emit(0x80|((c>>6)&63));_emit(0x80|(c&63));}}
static int64_t read_num(int bm){char b[64],*end;long long v;if(!fgets(b,sizeof(b),stdin))return int_lit(0,bm);errno=0;v=strtoll(b,&end,10);if(errno==ERANGE||end==b)return int_lit(0,bm);return bm?promote_val((int64_t)v):(int64_t)v;}
static int64_t read_char_(int bm){int b=getchar();if(b==EOF)return int_lit(-1,bm);if(b<0x80)return int_lit(b,bm);int n;int32_t v;if((b>>5)==6){n=1;v=b&31;}else if((b>>4)==14){n=2;v=b&15;}else if((b>>3)==30){n=3;v=b&7;}else return int_lit(-1,bm);while(n--){int c=getchar();if(c==EOF)return int_lit(-1,bm);v=(v<<6)|(c&63);}return int_lit(v,bm);}
