//! Generate Rust code from an Aheui CFG using the Stackifier algorithm.
//!
//! All control flow expressed as loop/break/continue — no match dispatch.
//! Compile with: rustc -C opt-level=3 -o program output.rs

use ahsembler::cfg::*;
use ahsembler::stackify::{Scope, ScopeKind, compute_scopes};
use std::collections::{BTreeSet, HashMap, HashSet};

const AGPL_NOTICE: &str = "\
// Generated by compaheuiler — https://github.com/youknowone/aheui-rust
// This code includes runtime components licensed under AGPL-3.0-or-later.
// Distributing binaries compiled from this code requires compliance with the AGPL.
";

/// Compile with bigint support (Val type instead of i64).
/// Generates code that depends on malachite-bigint at runtime, but the
/// codegen itself has no external dependencies.
pub fn compile_to_rs_bigint(source: &str) -> String {
    compile_to_rs_inner(source, true, ahsembler::OptimizationLevel::O3)
}

pub fn compile_to_rs_bigint_opt(source: &str, opt: ahsembler::OptimizationLevel) -> String {
    compile_to_rs_inner(source, true, opt)
}

pub fn compile_to_rs(source: &str) -> String {
    compile_to_rs_inner(source, false, ahsembler::OptimizationLevel::O3)
}

pub fn compile_to_rs_opt(source: &str, opt: ahsembler::OptimizationLevel) -> String {
    compile_to_rs_inner(source, false, opt)
}

fn compile_to_rs_inner(source: &str, bigint: bool, opt: ahsembler::OptimizationLevel) -> String {
    let mut cfg = ahsembler::compile_to_cfg_aot(source);
    if matches!(
        opt,
        ahsembler::OptimizationLevel::O2 | ahsembler::OptimizationLevel::O3
    ) {
        // Guard merging: fold StackGuard ok-paths into GuardDepth instructions
        for _ in 0..10 {
            let before = cfg.num_blocks();
            let states = ahsembler::cfg_optimize::analyze_stack_depths(&cfg);
            ahsembler::cfg_optimize::eliminate_guards(&mut cfg, &states);
            ahsembler::cfg_optimize::eliminate_guard_depth(&mut cfg, &states);
            ahsembler::cfg_optimize::thread_jumps(&mut cfg);
            ahsembler::cfg_optimize::merge_guard_ok(&mut cfg);
            ahsembler::cfg_optimize::merge_blocks(&mut cfg);
            ahsembler::cfg_optimize::eliminate_dead_blocks(&mut cfg);
            if cfg.num_blocks() == before {
                break;
            }
        }
    }
    if matches!(opt, ahsembler::OptimizationLevel::O3) {
        // Loop-aware guard elimination: remove guards in self-consistent loops
        let removed = ahsembler::cfg_optimize::eliminate_loop_guards(&mut cfg);
        if removed > 0 {
            for _ in 0..10 {
                let before = cfg.num_blocks();
                let states = ahsembler::cfg_optimize::analyze_stack_depths(&cfg);
                ahsembler::cfg_optimize::eliminate_guard_depth(&mut cfg, &states);
                ahsembler::cfg_optimize::thread_jumps(&mut cfg);
                ahsembler::cfg_optimize::merge_blocks(&mut cfg);
                ahsembler::cfg_optimize::eliminate_dead_blocks(&mut cfg);
                if cfg.num_blocks() == before {
                    break;
                }
            }
            let states = ahsembler::cfg_optimize::analyze_stack_depths(&cfg);
            ahsembler::cfg_optimize::fold_constants(&mut cfg, &states);
            ahsembler::cfg_optimize::peephole_cleanup(&mut cfg, &states);
        }
        // Chain guard elimination: linear sequences with back-edge-only fail targets
        let chain_removed = ahsembler::cfg_optimize::eliminate_chain_guards(&mut cfg);
        if chain_removed > 0 {
            for _ in 0..10 {
                let before = cfg.num_blocks();
                ahsembler::cfg_optimize::thread_jumps(&mut cfg);
                ahsembler::cfg_optimize::merge_blocks(&mut cfg);
                ahsembler::cfg_optimize::eliminate_dead_blocks(&mut cfg);
                if cfg.num_blocks() == before {
                    break;
                }
            }
        }
    }
    generate_rs_dispatch(&cfg, bigint)
}

/// Dispatch loop code generator: flat `loop { match _pc { ... } }`.
/// No nested scopes, no _goto — each block sets _pc and continues.
fn generate_rs_dispatch(cfg: &Cfg, bigint: bool) -> String {
    let mut out = String::with_capacity(16384);
    out.push_str(AGPL_NOTICE);
    out.push_str("#![allow(unused, unused_assignments, unused_mut)]\n");
    if bigint {
        #[cfg(feature = "num-bigint")]
        out.push_str("use num_bigint::BigInt;\n");
        #[cfg(not(feature = "num-bigint"))]
        out.push_str("use malachite_bigint::BigInt;\n");
        out.push_str(PRELUDE_INT_DUAL);
    } else {
        out.push_str(PRELUDE_INT_I64);
    }
    out.push_str(PRELUDE_COMMON);
    let states = ahsembler::cfg_optimize::analyze_stack_depths(cfg);
    let mut used: BTreeSet<usize> = BTreeSet::new();
    used.insert(0);
    for b in &cfg.blocks {
        for i in &b.instructions {
            match i {
                Inst::Sel(s) | Inst::Mov(s) => {
                    used.insert(*s);
                }
                _ => {}
            }
        }
    }
    let has_queue = used.contains(&QUEUE);
    let has_port = used.contains(&PORT);
    let has_special = has_queue || has_port;
    let vt = "*mut Int";
    let rt = "Int";
    let vz = if bigint {
        "Int::lit(0, _bm)"
    } else {
        "Int::ZERO"
    };

    out.push_str(&format!("pub unsafe fn aheui_main(bases: &mut [{vt}; 28], lengths: &mut [i32; 28], w: &mut impl std::io::Write) -> {rt} {{\n"));
    out.push_str("  let mut sp = SpecialStorage::new();\n");
    for &s in &used {
        out.push_str(&format!(
            "  let mut t{s}: {vt} = bases[{s}].add(lengths[{s}] as usize);\n"
        ));
    }
    out.push_str(&format!(
        "  let mut top: {vt} = t0;\n  let mut sel: usize = 0;\n  /*VARDECL*/\n"
    ));
    if bigint {
        out.push_str("  let mut _bm: bool = false;\n");
        // tops_snapshot: updated before arithmetic, used by dual_add/sub/mul for promote
        let mut tops_init = String::from("  let mut tops_snapshot: [*mut Int; 28] = [");
        for s in 0..28 {
            if used.contains(&s) && !is_special(s) {
                tops_init.push_str(&format!("t{s}"));
            } else {
                tops_init.push_str("std::ptr::null_mut()");
            }
            if s < 27 {
                tops_init.push_str(", ");
            }
        }
        tops_init.push_str("];\n");
        out.push_str(&tops_init);
    }
    let mut max_var: usize = 0;
    let ind = "      ";

    // Collect live block IDs in order
    let mut live_blocks: Vec<BlockId> = Vec::new();
    for block_id in 0..cfg.num_blocks() as BlockId {
        let entry_state = states.get(block_id as usize);
        if entry_state.map_or(true, |s| s.is_bottom()) {
            continue;
        }
        live_blocks.push(block_id);
    }
    let block_order: HashMap<BlockId, usize> = live_blocks
        .iter()
        .enumerate()
        .map(|(i, &b)| (b, i))
        .collect();

    out.push_str(&format!(
        "  let mut _pc: u32 = {};\n",
        block_order.get(&cfg.entry).copied().unwrap_or(0)
    ));
    let use_match = live_blocks.len() > 16; // match dispatch for large CFGs
    let has_dyn_sel = live_blocks.iter().any(|&bid| {
        states
            .get(bid as usize)
            .map_or(false, |s| s.selected.is_none())
    });
    out.push_str("  'dispatch: loop {\n");
    if use_match {
        out.push_str("    match _pc {\n");
    }

    for (seq_idx, &block_id) in live_blocks.iter().enumerate() {
        let block = cfg.block(block_id);
        let entry_state = states.get(block_id as usize);
        let entry_sel: Option<usize> = entry_state.and_then(|s| s.selected);
        let mut sel = entry_sel;
        let next_seq = seq_idx + 1;

        // Detect self-loop BranchZero for inner loop optimization
        let is_self_loop = matches!(&block.terminator,
            Terminator::BranchZero { on_zero, on_nonzero }
            if *on_zero == block_id || *on_nonzero == block_id);

        // Detect scan-to-zero: self-loop BranchZero on queue with only Dup+Mov(self)
        // Also detect guarded variant: GuardDepth(1) + Dup + Mov(self)
        let is_scan_to_zero = is_self_loop
            && entry_sel == Some(QUEUE)
            && matches!(&block.terminator, Terminator::BranchZero { .. })
            && {
                let insts = &block.instructions;
                (insts.len() == 2
                    && matches!(&insts[0], Inst::Dup)
                    && matches!(&insts[1], Inst::Mov(t) if *t == QUEUE))
                    || (insts.len() == 3
                        && matches!(&insts[0], Inst::GuardDepth { min_depth: 1, .. })
                        && matches!(&insts[1], Inst::Dup)
                        && matches!(&insts[2], Inst::Mov(t) if *t == QUEUE))
            };
        let scan_guard_fail = if is_scan_to_zero && block.instructions.len() == 3 {
            if let Inst::GuardDepth { fail, .. } = &block.instructions[0] {
                Some(block_order.get(fail).copied().unwrap_or(0))
            } else {
                None
            }
        } else {
            None
        };

        if use_match {
            out.push_str(&format!("    {seq_idx} => {{\n"));
        } else {
            out.push_str(&format!("    if _pc <= {seq_idx} {{\n"));
        }

        if is_scan_to_zero {
            if let Terminator::BranchZero {
                on_zero,
                on_nonzero,
            } = &block.terminator
            {
                let exit_target = if *on_nonzero == block_id {
                    on_zero
                } else {
                    on_nonzero
                };
                let exit_seq = block_order.get(exit_target).copied().unwrap_or(0);
                if let Some(guard_fail_seq) = scan_guard_fail {
                    out.push_str(&format!("{ind}  if sp.queue.is_empty() {{ _pc = {guard_fail_seq}; continue 'dispatch; }}\n"));
                }
                out.push_str(&format!("{ind}  sp.scan_to_zero();\n"));
                out.push_str(&format!("{ind}  _pc = {exit_seq}; continue 'dispatch;\n"));
            }
            // Close the block
            if use_match {
                out.push_str("    }\n");
            } else {
                out.push_str("    }\n");
            }
            continue;
        }

        if is_self_loop {
            out.push_str(&format!("{ind}  loop {{\n"));
        }

        // Entry sync: reload top from tN for sel-unknown blocks.
        // Skipped when ALL predecessors are sel-unknown with exit sync
        // (top already valid from previous block's exit sync: tN=top then top=tN is identity).
        // Still needed when sel-known predecessors exist (they use tN directly, top may be stale).
        let has_dyn_sel = live_blocks.iter().any(|&bid| {
            states
                .get(bid as usize)
                .map_or(false, |s| s.selected.is_none())
        });
        let skip_entry_sync = entry_sel.is_none() && has_dyn_sel;
        if entry_sel.is_none() && !skip_entry_sync {
            out.push_str(&format!("{ind}  match sel {{ "));
            for &s in &used {
                if !is_special(s) {
                    out.push_str(&format!("{s} => top = t{s}, "));
                }
            }
            out.push_str("_ => {} }\n");
        }

        // Instructions — Abs register allocation (no flush at Sel, only at control flow)
        let mut abs = Abs {
            stacks: HashMap::new(),
            active: entry_sel.unwrap_or(0),
            sel_known: entry_sel.is_some(),
            next_var: max_var,
        };
        let insts = &block.instructions;
        let mut ii = 0;
        let mut top_modified = false; // Track if 'top' pointer was modified in this block
        // Arithmetic: i64 mode uses Int:: directly, bigint uses dual-mode ops
        let op_str_fn = |kind: &BinOpKind, a: &str, b: &str| -> String {
            if bigint {
                match kind {
                    BinOpKind::Add => {
                        format!("dual_add({a}, {b}, &mut _bm, &bases, &mut tops_snapshot)")
                    }
                    BinOpKind::Sub => {
                        format!("dual_sub({a}, {b}, &mut _bm, &bases, &mut tops_snapshot)")
                    }
                    BinOpKind::Mul => {
                        format!("dual_mul({a}, {b}, &mut _bm, &bases, &mut tops_snapshot)")
                    }
                    BinOpKind::Div => format!("Int::div({a}, {b}, _bm)"),
                    BinOpKind::Mod => format!("Int::rem({a}, {b}, _bm)"),
                    BinOpKind::Cmp => format!(
                        "if Int::ge({a}, {b}, _bm) {{ Int::lit(1, _bm) }} else {{ Int::lit(0, _bm) }}"
                    ),
                }
            } else {
                match kind {
                    BinOpKind::Add => format!("Int::add({a}, {b})"),
                    BinOpKind::Sub => format!("Int::sub({a}, {b})"),
                    BinOpKind::Mul => format!("Int::mul({a}, {b})"),
                    BinOpKind::Div => format!("Int::div({a}, {b})"),
                    BinOpKind::Mod => format!("Int::rem({a}, {b})"),
                    BinOpKind::Cmp => {
                        format!("if Int::ge({a}, {b}) {{ Int::ONE }} else {{ Int::ZERO }}")
                    }
                }
            }
        };

        while ii < insts.len() {
            let inst = &insts[ii];
            let sp_known = sel.is_some_and(is_special);
            let ds = sel.is_none();
            let reg = sel.is_some() && !sp_known; // known + non-special → use Abs
            match inst {
                Inst::Push(v) => {
                    let cv = if bigint {
                        format!("Int::lit({v}, _bm)")
                    } else {
                        format!("Int::lit({v})")
                    };
                    if sp_known {
                        out.push_str(&format!("{ind}  sp.push({}, {cv});\n", sel.unwrap()));
                    } else if ds {
                        top_modified = true;
                        out.push_str(&format!("{ind}  if sel == {QUEUE} || sel == {PORT} {{ dyn_push_sp(&mut sp, sel, {cv}); }} else {{ *top = {cv}; top = top.add(1); }}\n"));
                    } else {
                        let var = abs.fresh();
                        out.push_str(&format!("{ind}  {var} = {cv};\n"));
                        abs.push(var);
                    }
                }
                Inst::Pop => {
                    if sp_known {
                        out.push_str(&format!("{ind}  sp.pop({});\n", sel.unwrap()));
                    } else if ds {
                        top_modified = true;
                        out.push_str(&format!("{ind}  if sel == {QUEUE} || sel == {PORT} {{ dyn_pop_sp(&mut sp, sel); }} else {{ top = top.sub(1); }}\n"));
                    } else if abs.pop().is_none() {
                        let t = abs.top_var();
                        out.push_str(&format!("{ind}  {t} = {t}.sub(1);\n"));
                    }
                }
                Inst::Dup => {
                    // Peephole: Dup + Mov(self) on special storage = rotate
                    if sp_known {
                        let s = sel.unwrap();
                        let next = insts.get(ii + 1);
                        if s == QUEUE {
                            if let Some(Inst::Mov(t)) = next {
                                if *t == s {
                                    // Dup + Mov(self) on queue = copy front to back
                                    out.push_str(&format!("{ind}  if let Some(&_v) = sp.queue.front() {{ sp.queue.push_back(_v); }}\n"));
                                    ii += 2;
                                    continue;
                                }
                            }
                        }
                        out.push_str(&format!("{ind}  sp.dup({s});\n"));
                    } else if ds {
                        top_modified = true;
                        out.push_str(&format!("{ind}  if sel == {QUEUE} || sel == {PORT} {{ dyn_dup_sp(&mut sp, sel); }} else {{ let _v = *top.sub(1); *top = _v; top = top.add(1); }}\n"));
                    } else {
                        ensure_depth(&mut out, &mut abs, 1, &format!("{ind}  "));
                        let v = abs.peek().unwrap().clone();
                        abs.push(v);
                    }
                }
                Inst::Swap => {
                    if sp_known {
                        out.push_str(&format!("{ind}  sp.swap({});\n", sel.unwrap()));
                    } else if ds {
                        top_modified = true;
                        out.push_str(&format!("{ind}  if sel == {QUEUE} || sel == {PORT} {{ dyn_swap_sp(&mut sp, sel); }} else {{ let (_a, _b) = (*top.sub(1), *top.sub(2)); *top.sub(1) = _b; *top.sub(2) = _a; }}\n"));
                    } else {
                        ensure_depth(&mut out, &mut abs, 2, &format!("{ind}  "));
                        let stk = abs.stacks.entry(abs.active).or_default();
                        let n = stk.len();
                        stk.swap(n - 1, n - 2);
                    }
                }
                Inst::BinOp(kind) => {
                    // In bigint mode, sync tops_snapshot before overflow-capable ops
                    if bigint && matches!(kind, BinOpKind::Add | BinOpKind::Sub | BinOpKind::Mul) {
                        for &s in &used {
                            if !is_special(s) {
                                out.push_str(&format!("{ind}  tops_snapshot[{s}] = t{s};\n"));
                            }
                        }
                    }
                    if sp_known {
                        let s = sel.unwrap();
                        let v1 = abs.fresh();
                        let v2 = abs.fresh();
                        let vr = abs.fresh();
                        out.push_str(&format!("{ind}  {v1} = sp.pop({s}); {v2} = sp.pop({s});\n{ind}  {vr} = {};\n{ind}  sp.push({s}, {vr});\n", op_str_fn(kind, &v2, &v1)));
                    } else if ds {
                        top_modified = true;
                        let v1 = abs.fresh();
                        let v2 = abs.fresh();
                        let vr = abs.fresh();
                        out.push_str(&format!("{ind}  if sel == {QUEUE} || sel == {PORT} {{\n{ind}    {v1} = dyn_pop_sp(&mut sp, sel); {v2} = dyn_pop_sp(&mut sp, sel);\n{ind}    {vr} = {};\n{ind}    dyn_push_sp(&mut sp, sel, {vr});\n{ind}  }} else {{\n{ind}    top = top.sub(2); {v2} = *top; {v1} = *top.add(1);\n{ind}    {vr} = {};\n{ind}    *top = {vr}; top = top.add(1);\n{ind}  }}\n", op_str_fn(kind, &v2, &v1), op_str_fn(kind, &v2, &v1)));
                    } else {
                        ensure_depth(&mut out, &mut abs, 2, &format!("{ind}  "));
                        let r1 = abs.pop().unwrap();
                        let r2 = abs.pop().unwrap();
                        let vr = abs.fresh();
                        out.push_str(&format!("{ind}  {vr} = {};\n", op_str_fn(kind, &r2, &r1)));
                        // After overflow-capable ops, promote live Abs vars that may still be raw i64
                        if bigint
                            && matches!(kind, BinOpKind::Add | BinOpKind::Sub | BinOpKind::Mul)
                        {
                            let mut live_vars: Vec<String> = Vec::new();
                            for (_, stack) in &abs.stacks {
                                for v in stack {
                                    live_vars.push(v.clone());
                                }
                            }
                            if !live_vars.is_empty() {
                                out.push_str(&format!("{ind}  if _bm {{ "));
                                for lv in &live_vars {
                                    out.push_str(&format!("{lv} = promote_val({lv}); "));
                                }
                                out.push_str("}\n");
                            }
                        }
                        abs.push(vr);
                    }
                }
                Inst::Sel(new_sel) => {
                    // NO flush — Abs tracks per-storage stacks
                    if ds && top_modified {
                        out.push_str(&format!("{ind}  match sel {{ "));
                        for &s in &used {
                            if !is_special(s) {
                                out.push_str(&format!("{s} => t{s} = top, "));
                            }
                        }
                        out.push_str("_ => {} }\n");
                        top_modified = false; // Reset after save-back
                    }
                    out.push_str(&format!("{ind}  sel = {new_sel};\n"));
                    abs.active = *new_sel;
                    abs.sel_known = true;
                    sel = Some(*new_sel);
                }
                Inst::Mov(target) => {
                    if sp_known {
                        let vr = abs.fresh();
                        out.push_str(&format!("{ind}  {vr} = sp.pop({});\n", sel.unwrap()));
                        if is_special(*target) {
                            out.push_str(&format!("{ind}  sp.push({target}, {vr});\n"));
                        } else {
                            out.push_str(&format!(
                                "{ind}  *t{target} = {vr}; t{target} = t{target}.add(1);\n"
                            ));
                        }
                    } else if ds {
                        top_modified = true;
                        let vr = abs.fresh();
                        out.push_str(&format!("{ind}  if sel == {QUEUE} || sel == {PORT} {{ {vr} = dyn_pop_sp(&mut sp, sel); }} else {{ top = top.sub(1); {vr} = *top; }}\n"));
                        if is_special(*target) {
                            out.push_str(&format!("{ind}  sp.push({target}, {vr});\n"));
                        } else {
                            out.push_str(&format!(
                                "{ind}  *t{target} = {vr}; t{target} = t{target}.add(1);\n"
                            ));
                        }
                    } else {
                        // reg mode: pop from current abs stack
                        ensure_depth(&mut out, &mut abs, 1, &format!("{ind}  "));
                        let vr = abs.pop().unwrap();
                        if is_special(*target) {
                            out.push_str(&format!("{ind}  sp.push({target}, {vr});\n"));
                        } else {
                            // Push to another non-special storage's abs stack
                            abs.stacks.entry(*target).or_default().push(vr);
                        }
                    }
                }
                Inst::PopNum => {
                    if sp_known {
                        let vr = abs.fresh();
                        out.push_str(&format!("{ind}  {vr} = sp.pop({});\n", sel.unwrap()));
                        out.push_str(&format!("{ind}  write_num(w, {vr});\n"));
                    } else if ds {
                        top_modified = true;
                        let vr = abs.fresh();
                        out.push_str(&format!("{ind}  if sel == {QUEUE} || sel == {PORT} {{ {vr} = dyn_pop_sp(&mut sp, sel); }} else {{ top = top.sub(1); {vr} = *top; }}\n"));
                        out.push_str(&format!("{ind}  write_num(w, {vr});\n"));
                    } else {
                        ensure_depth(&mut out, &mut abs, 1, &format!("{ind}  "));
                        let vr = abs.pop().unwrap();
                        out.push_str(&format!("{ind}  write_num(w, {vr});\n"));
                    }
                }
                Inst::PopChar => {
                    if sp_known {
                        let vr = abs.fresh();
                        out.push_str(&format!("{ind}  {vr} = sp.pop({});\n", sel.unwrap()));
                        out.push_str(&format!("{ind}  write_char(w, {vr});\n"));
                    } else if ds {
                        top_modified = true;
                        let vr = abs.fresh();
                        out.push_str(&format!("{ind}  if sel == {QUEUE} || sel == {PORT} {{ {vr} = dyn_pop_sp(&mut sp, sel); }} else {{ top = top.sub(1); {vr} = *top; }}\n"));
                        out.push_str(&format!("{ind}  write_char(w, {vr});\n"));
                    } else {
                        ensure_depth(&mut out, &mut abs, 1, &format!("{ind}  "));
                        let vr = abs.pop().unwrap();
                        out.push_str(&format!("{ind}  write_char(w, {vr});\n"));
                    }
                }
                Inst::PushNum => {
                    if reg {
                        abs.flush_all(&mut out, &format!("{ind}  "));
                    }
                    let vr = abs.fresh();
                    out.push_str(&format!(
                        "{ind}  w.flush().ok();\n{ind}  {vr} = read_num();\n"
                    ));
                    if sp_known {
                        out.push_str(&format!("{ind}  sp.push({}, {vr});\n", sel.unwrap()));
                    } else if ds {
                        top_modified = true;
                        out.push_str(&format!("{ind}  if sel == {QUEUE} || sel == {PORT} {{ dyn_push_sp(&mut sp, sel, {vr}); }} else {{ *top = {vr}; top = top.add(1); }}\n"));
                    } else {
                        abs.push(vr);
                    }
                }
                Inst::PushChar => {
                    if reg {
                        abs.flush_all(&mut out, &format!("{ind}  "));
                    }
                    let vr = abs.fresh();
                    out.push_str(&format!(
                        "{ind}  w.flush().ok();\n{ind}  {vr} = read_char();\n"
                    ));
                    if sp_known {
                        out.push_str(&format!("{ind}  sp.push({}, {vr});\n", sel.unwrap()));
                    } else if ds {
                        top_modified = true;
                        out.push_str(&format!("{ind}  if sel == {QUEUE} || sel == {PORT} {{ dyn_push_sp(&mut sp, sel, {vr}); }} else {{ *top = {vr}; top = top.add(1); }}\n"));
                    } else {
                        abs.push(vr);
                    }
                }
                Inst::GuardDepth { min_depth, fail } => {
                    // Flush abs for depth measurement
                    if reg {
                        abs.flush_all(&mut out, &format!("{ind}  "));
                    }
                    let t = if let Some(s) = sel {
                        format!("t{s}")
                    } else {
                        "top".into()
                    };
                    let depth_expr = if sp_known {
                        format!("sp.depth({}) as isize", sel.unwrap())
                    } else if ds {
                        format!(
                            "if sel == {QUEUE} || sel == {PORT} {{ sp.depth(sel) as isize }} else {{ {t}.offset_from(bases[sel]) }}"
                        )
                    } else {
                        let base = format!("bases[{}]", sel.unwrap());
                        format!("{t}.offset_from({base})")
                    };
                    if ds && top_modified {
                        out.push_str(&format!("{ind}  match sel {{ "));
                        for &s in &used {
                            if !is_special(s) {
                                out.push_str(&format!("{s} => t{s} = top, "));
                            }
                        }
                        out.push_str("_ => {} }\n");
                    }
                    let fail_seq = block_order.get(fail).copied().unwrap_or(0);
                    out.push_str(&format!("{ind}  if ({depth_expr}) < {min_depth} as isize {{ _pc = {fail_seq}; continue 'dispatch; }}\n"));
                }
            }
            ii += 1;
        }
        max_var = max_var.max(abs.next_var);

        // BranchZero: pop from abs BEFORE flush (avoids store→load round-trip)
        let brz_var = if let Terminator::BranchZero { .. } = &block.terminator {
            let reg = sel.is_some() && !sel.is_some_and(is_special);
            if reg {
                ensure_depth(&mut out, &mut abs, 1, &format!("{ind}  "));
                Some(abs.pop().unwrap())
            } else {
                None
            }
        } else {
            None
        };
        max_var = max_var.max(abs.next_var);

        // Flush abs + save-back before terminator
        abs.flush_all(&mut out, &format!("{ind}  "));
        let t = if let Some(s) = sel {
            format!("t{s}")
        } else {
            "top".into()
        };
        if sel.is_none() && top_modified {
            out.push_str(&format!("{ind}  match sel {{ "));
            for &s in &used {
                if !is_special(s) {
                    out.push_str(&format!("{s} => t{s} = top, "));
                }
            }
            out.push_str("_ => {} }\n");
        }

        // sel-known exit: sync top from tN so sel-unknown successors see correct top
        if has_dyn_sel && sel.is_some() && !sel.is_some_and(is_special) {
            out.push_str(&format!("{ind}  top = {t};\n"));
        }

        // Terminator — use seq indices for _pc, fallthrough for Goto(next)
        match &block.terminator {
            Terminator::Goto(target) => {
                let target_seq = block_order.get(target).copied().unwrap_or(0);
                if !use_match && target_seq == next_seq {
                    // Fallthrough — no _pc change needed, next if _pc <= N will match
                    out.push_str(&format!("{ind}  _pc = {next_seq};\n"));
                } else {
                    out.push_str(&format!("{ind}  _pc = {target_seq}; continue 'dispatch;\n"));
                }
            }
            Terminator::StackGuard {
                min_depth,
                ok,
                fail,
            } => {
                let sp_active = sel.is_some_and(is_special);
                let depth_expr = if sp_active {
                    format!("sp.depth({}) as isize", sel.unwrap())
                } else if sel.is_none() && has_special {
                    format!(
                        "if sel == {QUEUE} || sel == {PORT} {{ sp.depth(sel) as isize }} else {{ {t}.offset_from(bases[sel]) }}"
                    )
                } else {
                    let base = match sel {
                        Some(s) => format!("bases[{s}]"),
                        None => "bases[sel]".into(),
                    };
                    format!("{t}.offset_from({base})")
                };
                let ok_seq = block_order.get(ok).copied().unwrap_or(0);
                let fail_seq = block_order.get(fail).copied().unwrap_or(0);
                if ok_seq == next_seq {
                    out.push_str(&format!("{ind}  if ({depth_expr}) < {min_depth} as isize {{ _pc = {fail_seq}; continue 'dispatch; }}\n"));
                    out.push_str(&format!("{ind}  _pc = {next_seq};\n"));
                } else {
                    out.push_str(&format!("{ind}  _pc = if ({depth_expr}) >= {min_depth} as isize {{ {ok_seq} }} else {{ {fail_seq} }}; continue 'dispatch;\n"));
                }
            }
            Terminator::BranchZero {
                on_zero,
                on_nonzero,
            } => {
                let vr = if let Some(v) = brz_var.clone() {
                    v
                } else {
                    // Fallback: pop from actual memory (sp_known or sel=None)
                    let sp_active = sel.is_some_and(is_special);
                    let vr = abs.fresh();
                    max_var = max_var.max(abs.next_var);
                    if sp_active {
                        out.push_str(&format!("{ind}  {vr} = sp.pop({});\n", sel.unwrap()));
                    } else if sel.is_none() && has_special {
                        out.push_str(&format!("{ind}  if sel == {QUEUE} || sel == {PORT} {{ {vr} = dyn_pop_sp(&mut sp, sel); }} else {{ top = top.sub(1); {vr} = *top; }}\n"));
                    } else if sel.is_none() {
                        out.push_str(&format!("{ind}  top = top.sub(1); {vr} = *top;\n"));
                    } else {
                        out.push_str(&format!("{ind}  {t} = {t}.sub(1); {vr} = *{t};\n"));
                    }
                    vr
                };
                // Re-save after pop
                if sel.is_none() {
                    out.push_str(&format!("{ind}  match sel {{ "));
                    for &s in &used {
                        if !is_special(s) {
                            out.push_str(&format!("{s} => t{s} = top, "));
                        }
                    }
                    out.push_str("_ => {} }\n");
                }
                let zero_seq = block_order.get(on_zero).copied().unwrap_or(0);
                let nonzero_seq = block_order.get(on_nonzero).copied().unwrap_or(0);
                let bm_arg = if bigint { ", _bm" } else { "" };
                if is_self_loop && *on_nonzero == block_id {
                    out.push_str(&format!(
                        "{ind}  if Int::is_zero({vr}{bm_arg}) {{ _pc = {zero_seq}; break; }}\n"
                    ));
                } else if is_self_loop && *on_zero == block_id {
                    out.push_str(&format!(
                        "{ind}  if !Int::is_zero({vr}{bm_arg}) {{ _pc = {nonzero_seq}; break; }}\n"
                    ));
                } else {
                    let zero_check = if bigint {
                        format!("Int::is_zero({vr}, _bm)")
                    } else {
                        format!("Int::is_zero({vr})")
                    };
                    out.push_str(&format!("{ind}  _pc = if {zero_check} {{ {zero_seq} }} else {{ {nonzero_seq} }}; continue 'dispatch;\n"));
                }
            }
            Terminator::Halt => {
                out.push_str(&format!("{ind}  w.flush().ok();\n"));
                let base = match sel {
                    Some(s) => format!("bases[{s}]"),
                    None => "bases[sel]".into(),
                };
                out.push_str(&format!(
                    "{ind}  return if {t} > {base} {{ *{t}.sub(1) }} else {{ {vz} }};\n"
                ));
            }
        }

        // Close inner loop if self-loop block
        if is_self_loop {
            out.push_str(&format!("{ind}  }} // end inner loop\n"));
            out.push_str(&format!("{ind}  continue 'dispatch;\n"));
        }
        // Close the block
        if use_match {
            out.push_str("    }\n"); // close match arm
        } else {
            out.push_str("    }\n"); // close if block
        }
    }

    if use_match {
        out.push_str(&format!(
            "    _ => {{ break; }}\n    }}\n  }}\n  {vz}\n}}\n\n"
        ));
    } else {
        out.push_str(&format!("    break;\n  }}\n  {vz}\n}}\n\n"));
    }

    let mut var_decl = String::new();
    let var_init = if bigint { "Int(0)" } else { "Int::ZERO" }; // raw 0 in both modes
    for i in 0..max_var {
        var_decl.push_str(&format!("  let mut v{i}: Int = {var_init};\n"));
    }
    out = out.replacen("  /*VARDECL*/\n", &var_decl, 1);
    if bigint {
        out.push_str(MAIN_FN_DUAL);
    } else {
        out.push_str(MAIN_FN);
    }
    out
}

struct Abs {
    stacks: HashMap<usize, Vec<String>>,
    active: usize,
    sel_known: bool,
    next_var: usize,
}

impl Abs {
    fn new(sel: Option<usize>) -> Self {
        Abs {
            stacks: HashMap::new(),
            active: sel.unwrap_or(0),
            sel_known: sel.is_some(),
            next_var: 0,
        }
    }
    fn from_snap(stacks: HashMap<usize, Vec<String>>, nv: usize, sel: Option<usize>) -> Self {
        Abs {
            stacks,
            active: sel.unwrap_or(0),
            sel_known: sel.is_some(),
            next_var: nv,
        }
    }
    fn fresh(&mut self) -> String {
        let n = self.next_var;
        self.next_var += 1;
        format!("v{n}")
    }
    fn top_var(&self) -> String {
        if self.sel_known {
            format!("t{}", self.active)
        } else {
            "top".into()
        }
    }
    fn push(&mut self, var: String) {
        self.stacks.entry(self.active).or_default().push(var);
    }
    fn pop(&mut self) -> Option<String> {
        self.stacks.entry(self.active).or_default().pop()
    }
    fn len(&self) -> usize {
        self.stacks.get(&self.active).map_or(0, |v| v.len())
    }
    fn peek(&self) -> Option<&String> {
        self.stacks.get(&self.active).and_then(|v| v.last())
    }
    fn snapshot(&self) -> (HashMap<usize, Vec<String>>, usize) {
        (self.stacks.clone(), self.next_var)
    }
    fn flush_all(&mut self, out: &mut String, indent: &str) {
        let active = self.active;
        let active_top = self.top_var();
        let mut keys: Vec<usize> = self.stacks.keys().copied().collect();
        keys.sort();
        for s in keys {
            let stack = self.stacks.get_mut(&s).unwrap();
            if stack.is_empty() {
                continue;
            }
            let t = if s == active {
                active_top.clone()
            } else {
                format!("t{s}")
            };
            for var in stack.drain(..) {
                out.push_str(&format!("{indent}*{t} = {var}; {t} = {t}.add(1);\n"));
            }
        }
    }
}

fn ensure_depth(out: &mut String, abs: &mut Abs, depth: usize, indent: &str) {
    if abs.len() >= depth {
        return;
    }
    let need = depth - abs.len();
    let t = abs.top_var();
    let active = abs.active;
    let mut loaded = Vec::with_capacity(need);
    for i in 0..need {
        let var = abs.fresh();
        out.push_str(&format!("{indent}{var} = *{t}.sub({});\n", need - i));
        loaded.push(var);
    }
    out.push_str(&format!("{indent}{t} = {t}.sub({need});\n"));
    let stack = abs.stacks.entry(active).or_default();
    let mut existing = std::mem::take(stack);
    stack.extend(loaded);
    stack.append(&mut existing);
}

fn generate_rs(cfg: &Cfg) -> String {
    let mut out = String::with_capacity(16384);
    out.push_str(AGPL_NOTICE);
    out.push_str("#![allow(unused, unused_assignments, unused_mut)]\n");
    out.push_str(PRELUDE_INT_I64);
    out.push_str(PRELUDE_COMMON);
    let states = ahsembler::cfg_optimize::analyze_stack_depths(cfg);
    let rpo = cfg.reverse_postorder();
    let preds = cfg.predecessors();
    let mut used: BTreeSet<usize> = BTreeSet::new();
    used.insert(0);
    for b in &cfg.blocks {
        for i in &b.instructions {
            match i {
                Inst::Sel(s) | Inst::Mov(s) => {
                    used.insert(*s);
                }
                _ => {}
            }
        }
    }
    let mut rpo_pos: HashMap<BlockId, usize> = HashMap::new();
    for (i, &bid) in rpo.iter().enumerate() {
        rpo_pos.insert(bid, i);
    }
    let scopes = compute_scopes(cfg, &rpo);
    let mut opens_at: HashMap<usize, Vec<usize>> = HashMap::new();
    let mut closes_at: HashMap<usize, Vec<usize>> = HashMap::new();
    for (si, scope) in scopes.iter().enumerate() {
        opens_at.entry(scope.open).or_default().push(si);
        closes_at.entry(scope.close).or_default().push(si);
    }
    let can_inherit = {
        let mut ci = vec![false; cfg.num_blocks()];
        for block_id in 0..cfg.num_blocks() {
            let bp = &preds[block_id];
            if bp.len() == 1 {
                let pred = bp[0];
                let ok = match &cfg.block(pred).terminator {
                    Terminator::Goto(_) => true,
                    Terminator::StackGuard { ok, .. } if *ok == block_id as BlockId => true,
                    Terminator::BranchZero { .. } => true,
                    _ => false,
                };
                if ok && pred < block_id as BlockId {
                    ci[block_id] = true;
                }
            }
        }
        ci
    };
    let has_queue = used.contains(&QUEUE);
    let has_port = used.contains(&PORT);
    let has_special = has_queue || has_port;

    out.push_str("pub unsafe fn aheui_main(bases: &mut [*mut i64; 28], lengths: &mut [i32; 28], w: &mut impl std::io::Write) -> i64 {\n");
    out.push_str("  let mut sp = SpecialStorage::new();\n");
    for &s in &used {
        out.push_str(&format!(
            "  let mut t{s}: *mut i64 = bases[{s}].add(lengths[{s}] as usize);\n"
        ));
    }
    out.push_str("  let mut top: *mut i64 = t0;\n  let mut sel: usize = 0;\n  /*VARDECL*/\n");
    let mut max_var: usize = 0;
    let mut block_exit: HashMap<BlockId, (HashMap<usize, Vec<String>>, usize)> = HashMap::new();
    let mut depth: usize = 1;
    let indent = |d: usize| -> String { "  ".repeat(d) };

    // Detect if _goto dispatch is needed: any Loop with extended open (open < header_rpo)
    let needs_goto = scopes
        .iter()
        .any(|s| s.kind == ScopeKind::Loop && s.open < rpo_pos[&s.label]);

    // Pre-compute which RPO indices are _goto targets (need guards).
    let mut goto_targets: HashSet<usize> = HashSet::new();
    if needs_goto {
        // Simulate emit_jump for all terminators to find _goto assignments.
        for (order_idx, &block_id) in rpo.iter().enumerate() {
            let block = cfg.block(block_id);
            let mut collect_target = |target: BlockId| {
                if let Some(&tp) = rpo_pos.get(&target) {
                    if tp <= order_idx {
                        // Back edge with extended open: _goto = tp
                        for s in &scopes {
                            if s.kind == ScopeKind::Loop && s.label == target && s.open < tp {
                                goto_targets.insert(tp);
                            }
                        }
                    } else {
                        // Forward jump: check if exact scope exists
                        let exact = scopes.iter().any(|s| s.open <= order_idx && s.close == tp);
                        if !exact {
                            // Would use _goto dispatch
                            goto_targets.insert(tp);
                        }
                    }
                }
            };
            match &block.terminator {
                Terminator::Goto(t) => {
                    collect_target(*t);
                }
                Terminator::StackGuard { ok, fail, .. } => {
                    collect_target(*ok);
                    collect_target(*fail);
                }
                Terminator::BranchZero {
                    on_zero,
                    on_nonzero,
                } => {
                    collect_target(*on_zero);
                    collect_target(*on_nonzero);
                }
                Terminator::Halt => {}
            }
        }
    }

    let mut goto_guard_open = false;
    let mut guard_inlined: HashSet<usize> = HashSet::new(); // ok blocks inlined after guard — skip _goto guard + entry sync

    for (order_idx, &block_id) in rpo.iter().enumerate() {
        // Close goto guard before scope boundaries
        let has_scope_close = closes_at.contains_key(&order_idx);
        let has_scope_open = opens_at.contains_key(&order_idx);
        let is_goto_target = goto_targets.contains(&order_idx);

        // Must close guard before scope close/open or at goto targets
        if goto_guard_open && (has_scope_close || has_scope_open || is_goto_target) {
            depth -= 1;
            out.push_str(&format!("{}}}\n", indent(depth)));
            goto_guard_open = false;
        }

        // Close scopes
        if let Some(closing) = closes_at.get(&order_idx) {
            for &si in closing.iter().rev() {
                depth -= 1;
                let s = &scopes[si];
                match s.kind {
                    ScopeKind::Loop => {
                        out.push_str(&format!("{}}} // end loop l{}\n", indent(depth), s.label))
                    }
                    ScopeKind::Forward => {
                        out.push_str(&format!("{}}} // end fwd f{}\n", indent(depth), s.label))
                    }
                }
            }
        }
        // Open scopes
        if let Some(opening) = opens_at.get(&order_idx) {
            for &si in opening {
                let s = &scopes[si];
                match s.kind {
                    ScopeKind::Loop => {
                        out.push_str(&format!("{}'l{}: loop {{\n", indent(depth), s.label));
                        depth += 1;
                        if needs_goto {
                            let ind2 = indent(depth);
                            out.push_str(&format!("{ind2}if _goto > 0 && (_goto < {} || _goto >= {}) {{ break 'l{}; }}\n", s.open, s.close, s.label));
                        }
                    }
                    ScopeKind::Forward => {
                        out.push_str(&format!("{}'f{}: {{\n", indent(depth), s.label));
                        depth += 1;
                    }
                }
            }
        }
        let ind = indent(depth);
        let block = cfg.block(block_id);
        let entry_sel: Option<usize> = states.get(block_id as usize).and_then(|s| s.selected);
        // Goto dispatch: open guard if not already open (skip for guard-inlined blocks)
        let mut goto_guard_opened = false;
        let skip_guard = guard_inlined.contains(&order_idx);
        if needs_goto && !skip_guard {
            if is_goto_target {
                // Target block: reset _goto and re-sync top/sel
                out.push_str(&format!("{ind}if _goto == {order_idx} {{ _goto = 0; "));
                if let Some(s) = entry_sel {
                    out.push_str(&format!("top = t{s}; sel = {s}; "));
                } else {
                    out.push_str("match sel { ");
                    for &s in &used {
                        if !is_special(s) {
                            out.push_str(&format!("{s} => top = t{s}, "));
                        }
                    }
                    out.push_str("_ => {} } ");
                }
                out.push_str("}\n");
            }
            if !goto_guard_open {
                out.push_str(&format!("{ind}if _goto == 0 {{\n"));
                depth += 1;
                goto_guard_opened = true;
                goto_guard_open = true;
            }
        }
        let ind = indent(depth);
        let mut sel = entry_sel;
        out.push_str(&format!("{ind}// B{block_id}\n"));

        let mut abs = if can_inherit[block_id as usize] || skip_guard {
            let pred = preds[block_id as usize][0];
            if let Some((stacks, nv)) = block_exit.remove(&pred) {
                Abs::from_snap(stacks, nv, entry_sel)
            } else {
                Abs::new(entry_sel)
            }
        } else {
            if let Some(s) = entry_sel {
                out.push_str(&format!("{ind}top = t{s}; sel = {s};\n"));
            } else {
                // entry_sel unknown: sync top from runtime sel
                out.push_str(&format!("{ind}match sel {{ "));
                for &s in &used {
                    if !is_special(s) {
                        out.push_str(&format!("{s} => top = t{s}, "));
                    }
                }
                out.push_str("_ => {} }\n");
            }
            Abs::new(entry_sel)
        };

        let mut guard_fail_target: Option<(BlockId, usize, String)> = None;
        for inst in &block.instructions {
            let t = abs.top_var();
            let sp_known = is_special(abs.active);
            // dyn_sel: entry_sel unknown. If has_special, need sp dispatch; otherwise just use top.
            let dyn_sel = !abs.sel_known && has_special;
            let dyn_top = !abs.sel_known && !has_special;
            match inst {
                Inst::Push(v) => {
                    if sp_known {
                        out.push_str(&format!("{ind}sp.push({}, {v});\n", abs.active));
                    } else if dyn_sel {
                        out.push_str(&format!("{ind}if sel == {QUEUE} || sel == {PORT} {{ sp.push(sel, {v}); }} else {{ *top = {v}; top = top.add(1); }}\n"));
                    } else if dyn_top {
                        out.push_str(&format!("{ind}*top = {v}; top = top.add(1);\n"));
                    } else {
                        let var = abs.fresh();
                        out.push_str(&format!("{ind}{var} = {v};\n"));
                        abs.push(var);
                    }
                }
                Inst::Pop => {
                    if sp_known {
                        out.push_str(&format!("{ind}sp.pop({});\n", abs.active));
                    } else if dyn_sel {
                        out.push_str(&format!("{ind}if sel == {QUEUE} || sel == {PORT} {{ sp.pop(sel); }} else {{ top = top.sub(1); }}\n"));
                    } else if dyn_top {
                        out.push_str(&format!("{ind}top = top.sub(1);\n"));
                    } else if abs.pop().is_none() {
                        out.push_str(&format!("{ind}{t} = {t}.sub(1);\n"));
                    }
                }
                Inst::Dup => {
                    if sp_known {
                        out.push_str(&format!("{ind}sp.dup({});\n", abs.active));
                    } else if dyn_sel {
                        out.push_str(&format!("{ind}if sel == {QUEUE} || sel == {PORT} {{ sp.dup(sel); }} else {{ let _v = *top.sub(1); *top = _v; top = top.add(1); }}\n"));
                    } else if dyn_top {
                        out.push_str(&format!(
                            "{ind}{{ let _v = *top.sub(1); *top = _v; top = top.add(1); }}\n"
                        ));
                    } else {
                        ensure_depth(&mut out, &mut abs, 1, &ind);
                        let top_val = abs.peek().unwrap().clone();
                        let var = abs.fresh();
                        out.push_str(&format!("{ind}{var} = {top_val};\n"));
                        abs.push(var);
                    }
                }
                Inst::Swap => {
                    if sp_known {
                        out.push_str(&format!("{ind}sp.swap({});\n", abs.active));
                    } else if dyn_sel {
                        out.push_str(&format!("{ind}if sel == {QUEUE} || sel == {PORT} {{ sp.swap(sel); }} else {{ let (_a, _b) = (*top.sub(1), *top.sub(2)); *top.sub(1) = _b; *top.sub(2) = _a; }}\n"));
                    } else if dyn_top {
                        out.push_str(&format!("{ind}{{ let (_a, _b) = (*top.sub(1), *top.sub(2)); *top.sub(1) = _b; *top.sub(2) = _a; }}\n"));
                    } else {
                        ensure_depth(&mut out, &mut abs, 2, &ind);
                        let len = abs.len();
                        let active = abs.active;
                        abs.stacks.get_mut(&active).unwrap().swap(len - 1, len - 2);
                    }
                }
                Inst::BinOp(kind) => {
                    let op_str = |a: &str, b: &str| -> String {
                        match kind {
                            BinOpKind::Add => format!("{a}.wrapping_add({b})"),
                            BinOpKind::Sub => format!("{a}.wrapping_sub({b})"),
                            BinOpKind::Mul => format!("{a}.wrapping_mul({b})"),
                            BinOpKind::Div => {
                                format!("if {b} != 0 {{ {a}.wrapping_div({b}) }} else {{ 0 }}")
                            }
                            BinOpKind::Mod => {
                                format!("if {b} != 0 {{ {a}.wrapping_rem({b}) }} else {{ 0 }}")
                            }
                            BinOpKind::Cmp => format!("if {a} >= {b} {{ 1 }} else {{ 0 }}"),
                        }
                    };
                    if sp_known {
                        let s = abs.active;
                        let var1 = abs.fresh();
                        let var2 = abs.fresh();
                        let var = abs.fresh();
                        out.push_str(&format!("{ind}{var1} = sp.pop({s});\n{ind}{var2} = sp.pop({s});\n{ind}{var} = {};\n{ind}sp.push({s}, {var});\n", op_str(&var2, &var1)));
                    } else if dyn_sel {
                        let var1 = abs.fresh();
                        let var2 = abs.fresh();
                        let var = abs.fresh();
                        out.push_str(&format!("{ind}if sel == {QUEUE} || sel == {PORT} {{\n{ind}  {var1} = sp.pop(sel); {var2} = sp.pop(sel);\n{ind}  {var} = {};\n{ind}  sp.push(sel, {var});\n{ind}}} else {{\n{ind}  top = top.sub(2); {var2} = *top; {var1} = *top.add(1);\n{ind}  {var} = {};\n{ind}  *top = {var}; top = top.add(1);\n{ind}}}\n", op_str(&var2, &var1), op_str(&var2, &var1)));
                    } else if dyn_top {
                        let var1 = abs.fresh();
                        let var2 = abs.fresh();
                        let var = abs.fresh();
                        out.push_str(&format!("{ind}top = top.sub(2); {var2} = *top; {var1} = *top.add(1);\n{ind}{var} = {};\n{ind}*top = {var}; top = top.add(1);\n", op_str(&var2, &var1)));
                    } else {
                        ensure_depth(&mut out, &mut abs, 2, &ind);
                        let r1 = abs.pop().unwrap();
                        let r2 = abs.pop().unwrap();
                        let var = abs.fresh();
                        out.push_str(&format!("{ind}{var} = {};\n", op_str(&r2, &r1)));
                        abs.push(var);
                    }
                }
                Inst::Sel(new_sel) => {
                    if !is_special(abs.active) {
                        abs.flush_all(&mut out, &ind);
                    }
                    if sel.is_none() {
                        out.push_str(&format!("{ind}match sel {{ "));
                        for &s in &used {
                            if !is_special(s) {
                                out.push_str(&format!("{s} => t{s} = top, "));
                            }
                        }
                        out.push_str("_ => {} }\n");
                    }
                    out.push_str(&format!("{ind}sel = {new_sel};\n"));
                    if !is_special(*new_sel) {
                        out.push_str(&format!("{ind}top = t{new_sel};\n"));
                    }
                    abs.active = *new_sel;
                    abs.sel_known = true;
                    sel = Some(*new_sel);
                }
                Inst::Mov(target) => {
                    if sp_known {
                        let var = abs.fresh();
                        out.push_str(&format!("{ind}{var} = sp.pop({});\n", abs.active));
                        if is_special(*target) {
                            out.push_str(&format!("{ind}sp.push({target}, {var});\n"));
                        } else {
                            out.push_str(&format!(
                                "{ind}*t{target} = {var}; t{target} = t{target}.add(1);\n"
                            ));
                        }
                    } else if dyn_sel {
                        let var = abs.fresh();
                        out.push_str(&format!("{ind}if sel == {QUEUE} || sel == {PORT} {{ {var} = sp.pop(sel); }} else {{ top = top.sub(1); {var} = *top; }}\n"));
                        if is_special(*target) {
                            out.push_str(&format!("{ind}sp.push({target}, {var});\n"));
                        } else {
                            out.push_str(&format!(
                                "{ind}*t{target} = {var}; t{target} = t{target}.add(1);\n"
                            ));
                        }
                    } else if dyn_top {
                        let var = abs.fresh();
                        out.push_str(&format!("{ind}top = top.sub(1); {var} = *top;\n"));
                        if is_special(*target) {
                            out.push_str(&format!("{ind}sp.push({target}, {var});\n"));
                        } else {
                            out.push_str(&format!(
                                "{ind}*t{target} = {var}; t{target} = t{target}.add(1);\n"
                            ));
                        }
                    } else {
                        ensure_depth(&mut out, &mut abs, 1, &ind);
                        let val = abs.pop().unwrap();
                        if is_special(*target) {
                            out.push_str(&format!("{ind}sp.push({target}, {val});\n"));
                        } else {
                            out.push_str(&format!(
                                "{ind}*t{target} = {val}; t{target} = t{target}.add(1);\n"
                            ));
                        }
                    }
                }
                Inst::PopNum => {
                    if sp_known {
                        let var = abs.fresh();
                        out.push_str(&format!(
                            "{ind}{var} = sp.pop({});\n{ind}write_num(w, {var});\n",
                            abs.active
                        ));
                    } else if dyn_sel {
                        let var = abs.fresh();
                        out.push_str(&format!("{ind}if sel == {QUEUE} || sel == {PORT} {{ {var} = sp.pop(sel); }} else {{ top = top.sub(1); {var} = *top; }}\n{ind}write_num(w, {var});\n"));
                    } else if dyn_top {
                        let var = abs.fresh();
                        out.push_str(&format!(
                            "{ind}top = top.sub(1); {var} = *top;\n{ind}write_num(w, {var});\n"
                        ));
                    } else {
                        ensure_depth(&mut out, &mut abs, 1, &ind);
                        let val = abs.pop().unwrap();
                        out.push_str(&format!("{ind}write_num(w, {val});\n"));
                    }
                }
                Inst::PopChar => {
                    if sp_known {
                        let var = abs.fresh();
                        out.push_str(&format!(
                            "{ind}{var} = sp.pop({});\n{ind}write_char(w, {var});\n",
                            abs.active
                        ));
                    } else if dyn_sel {
                        let var = abs.fresh();
                        out.push_str(&format!("{ind}if sel == {QUEUE} || sel == {PORT} {{ {var} = sp.pop(sel); }} else {{ top = top.sub(1); {var} = *top; }}\n{ind}write_char(w, {var});\n"));
                    } else if dyn_top {
                        let var = abs.fresh();
                        out.push_str(&format!(
                            "{ind}top = top.sub(1); {var} = *top;\n{ind}write_char(w, {var});\n"
                        ));
                    } else {
                        ensure_depth(&mut out, &mut abs, 1, &ind);
                        let val = abs.pop().unwrap();
                        out.push_str(&format!("{ind}write_char(w, {val});\n"));
                    }
                }
                Inst::PushNum => {
                    let var = abs.fresh();
                    if sp_known {
                        out.push_str(&format!(
                            "{ind}{var} = read_num();\n{ind}sp.push({}, {var});\n",
                            abs.active
                        ));
                    } else if dyn_sel {
                        out.push_str(&format!("{ind}{var} = read_num();\n{ind}if sel == {QUEUE} || sel == {PORT} {{ sp.push(sel, {var}); }} else {{ *top = {var}; top = top.add(1); }}\n"));
                    } else if dyn_top {
                        out.push_str(&format!(
                            "{ind}{var} = read_num();\n{ind}*top = {var}; top = top.add(1);\n"
                        ));
                    } else {
                        abs.flush_all(&mut out, &ind);
                        out.push_str(&format!("{ind}{var} = read_num();\n"));
                        abs.push(var);
                    }
                }
                Inst::PushChar => {
                    let var = abs.fresh();
                    if sp_known {
                        out.push_str(&format!(
                            "{ind}{var} = read_char();\n{ind}sp.push({}, {var});\n",
                            abs.active
                        ));
                    } else if dyn_sel {
                        out.push_str(&format!("{ind}{var} = read_char();\n{ind}if sel == {QUEUE} || sel == {PORT} {{ sp.push(sel, {var}); }} else {{ *top = {var}; top = top.add(1); }}\n"));
                    } else if dyn_top {
                        out.push_str(&format!(
                            "{ind}{var} = read_char();\n{ind}*top = {var}; top = top.add(1);\n"
                        ));
                    } else {
                        abs.flush_all(&mut out, &ind);
                        out.push_str(&format!("{ind}{var} = read_char();\n"));
                        abs.push(var);
                    }
                }
                Inst::GuardDepth { min_depth, fail } => {
                    // Inline depth guard: check and jump to fail if insufficient
                    abs.flush_all(&mut out, &ind);
                    if !abs.sel_known {
                        out.push_str(&format!("{ind}match sel {{ "));
                        for &s in &used {
                            if !is_special(s) {
                                out.push_str(&format!("{s} => t{s} = top, "));
                            }
                        }
                        out.push_str("_ => {} }\n");
                    }
                    let gsp = is_special(abs.active);
                    let gds = !abs.sel_known;
                    let gt = abs.top_var();
                    let depth_expr = if gsp {
                        format!("sp.depth({}) as isize", abs.active)
                    } else if gds && has_special {
                        format!(
                            "if sel == {QUEUE} || sel == {PORT} {{ sp.depth(sel) as isize }} else {{ {gt}.offset_from(bases[sel]) }}"
                        )
                    } else {
                        let base = if abs.sel_known {
                            format!("bases[{}]", abs.active)
                        } else {
                            "bases[sel]".into()
                        };
                        format!("{gt}.offset_from({base})")
                    };
                    // Store fail target for emit_jump — use _guard_fail variable
                    guard_fail_target = Some((*fail, *min_depth, depth_expr));
                }
            }
        }

        if abs.next_var > max_var {
            max_var = abs.next_var;
        }
        let t = abs.top_var();
        let next_rpo = rpo.get(order_idx + 1).copied();
        let scope_closes_before = |target_rpo: usize| -> bool {
            scopes
                .iter()
                .any(|s| s.close > order_idx && s.close <= target_rpo)
        };
        let emit_jump = |out: &mut String, target: BlockId, ind: &str, force: bool| {
            if let Some(&tp) = rpo_pos.get(&target) {
                if tp <= order_idx {
                    // Back edge: if this loop has extended open, set _goto to
                    // skip pre-header blocks on re-entry.
                    if needs_goto {
                        for s in &scopes {
                            if s.kind == ScopeKind::Loop
                                && s.label == target
                                && s.open <= order_idx
                                && s.open < tp
                            {
                                out.push_str(&format!("{ind}_goto = {tp};\n"));
                                break;
                            }
                        }
                    }
                    out.push_str(&format!("{ind}continue 'l{target};\n"));
                    return;
                }
                if !force && Some(target) == next_rpo && !scope_closes_before(tp) {
                    return;
                }
                let mut best: Option<&Scope> = None;
                for s in &scopes {
                    if s.open > order_idx || s.close < tp {
                        continue;
                    }
                    let dominated = match best {
                        None => true,
                        Some(b) => {
                            if s.close == tp && b.close != tp {
                                true
                            } else if s.close == tp {
                                s.open < b.open
                            } else {
                                b.close != tp && s.close < b.close
                            }
                        }
                    };
                    if dominated {
                        best = Some(s);
                    }
                }
                let exact = best.filter(|s| s.close == tp);
                if let Some(s) = exact {
                    let prefix = if s.kind == ScopeKind::Loop { "l" } else { "f" };
                    out.push_str(&format!("{ind}break '{prefix}{};\n", s.label));
                } else if !needs_goto {
                    // No _goto available; use wider scope as last resort
                    if let Some(s) = best {
                        let prefix = if s.kind == ScopeKind::Loop { "l" } else { "f" };
                        out.push_str(&format!("{ind}break '{prefix}{};\n", s.label));
                    }
                } else if tp > order_idx {
                    // No scope covers [source, target). Use goto dispatch.
                    out.push_str(&format!("{ind}_goto = {tp};\n"));
                    // Find innermost scope containing source but NOT target (safe to break).
                    // If all scopes containing source also contain target, continue the innermost loop.
                    let mut break_scope: Option<&Scope> = None;
                    let mut cont_loop: Option<&Scope> = None;
                    for s in &scopes {
                        if s.open <= order_idx && s.close > order_idx {
                            if tp >= s.close {
                                // Target is past this scope — safe to break
                                match break_scope {
                                    None => break_scope = Some(s),
                                    Some(n) => {
                                        if (s.close - s.open) < (n.close - n.open) {
                                            break_scope = Some(s);
                                        }
                                    }
                                }
                            } else if s.kind == ScopeKind::Loop {
                                // Target is inside this loop — continue to restart
                                match cont_loop {
                                    None => cont_loop = Some(s),
                                    Some(n) => {
                                        if (s.close - s.open) < (n.close - n.open) {
                                            cont_loop = Some(s);
                                        }
                                    }
                                }
                            }
                        }
                    }
                    if let Some(s) = break_scope {
                        let p = if s.kind == ScopeKind::Loop { "l" } else { "f" };
                        out.push_str(&format!("{ind}break '{p}{};\n", s.label));
                    } else if let Some(s) = cont_loop {
                        out.push_str(&format!("{ind}continue 'l{};\n", s.label));
                    }
                }
            }
        };

        // Helper: save top→tN when dyn_sel was active.
        let needs_save_back = entry_sel.is_none() && !abs.sel_known;
        let emit_save_back = |out: &mut String, ind: &str, used: &BTreeSet<usize>| {
            out.push_str(&format!("{ind}match sel {{ "));
            for &s in used {
                if !is_special(s) {
                    out.push_str(&format!("{s} => t{s} = top, "));
                }
            }
            out.push_str("_ => {} }\n");
        };

        // Emit deferred GuardDepth fail jump (now that emit_jump is available)
        if let Some((fail_target, min_depth, depth_expr)) = guard_fail_target {
            out.push_str(&format!(
                "{ind}if ({depth_expr}) < {min_depth} as isize {{\n"
            ));
            emit_jump(&mut out, fail_target, &format!("{ind}  "), true);
            out.push_str(&format!("{ind}}}\n"));
        }

        match &block.terminator {
            Terminator::Goto(target) => {
                if needs_save_back {
                    abs.flush_all(&mut out, &ind);
                    emit_save_back(&mut out, &ind, &used);
                } else if !can_inherit[*target as usize] {
                    abs.flush_all(&mut out, &ind);
                }
                if can_inherit[*target as usize] {
                    block_exit.insert(block_id, abs.snapshot());
                }
                emit_jump(&mut out, *target, &ind, false);
            }
            Terminator::StackGuard {
                min_depth,
                ok,
                fail,
            } => {
                if needs_save_back {
                    abs.flush_all(&mut out, &ind);
                    emit_save_back(&mut out, &ind, &used);
                } else {
                    abs.flush_all(&mut out, &ind);
                }
                let sp_active = sel.is_some_and(is_special);
                let dyn_guard = sel.is_none();
                let depth_expr = if sp_active {
                    format!("sp.depth({}) as isize", sel.unwrap())
                } else if dyn_guard && has_special {
                    format!(
                        "if sel == {QUEUE} || sel == {PORT} {{ sp.depth(sel) as isize }} else {{ {t}.offset_from(bases[sel]) }}"
                    )
                } else {
                    let base = match sel {
                        Some(s) => format!("bases[{s}]"),
                        None => "bases[sel]".into(),
                    };
                    format!("{t}.offset_from({base})")
                };

                // Inline ok block: when ok is next in RPO, single-pred, no scope boundary
                let ok_rpo = rpo_pos.get(ok).copied();
                let can_inline_ok = ok_rpo == Some(order_idx + 1)
                    && preds[*ok as usize].len() == 1
                    && !closes_at.contains_key(&(order_idx + 1))
                    && !opens_at.contains_key(&(order_idx + 1))
                    && !goto_targets.contains(&(order_idx + 1));

                if can_inline_ok {
                    // Emit fail path only; ok block follows as fallthrough
                    out.push_str(&format!(
                        "{ind}if ({depth_expr}) < {min_depth} as isize {{\n"
                    ));
                    emit_jump(&mut out, *fail, &format!("{ind}  "), true);
                    out.push_str(&format!("{ind}}}\n"));
                    // Mark ok block: skip its _goto guard and entry sync
                    guard_inlined.insert(order_idx + 1);
                    // Save abs state for ok block to inherit
                    block_exit.insert(block_id, abs.snapshot());
                } else {
                    let fail_is_next =
                        Some(*fail) == next_rpo && !scope_closes_before(rpo_pos[fail]);
                    if fail_is_next {
                        out.push_str(&format!(
                            "{ind}if ({depth_expr}) >= {min_depth} as isize {{\n"
                        ));
                        emit_jump(&mut out, *ok, &format!("{ind}  "), true);
                        out.push_str(&format!("{ind}}}\n"));
                    } else {
                        out.push_str(&format!(
                            "{ind}if ({depth_expr}) < {min_depth} as isize {{\n"
                        ));
                        emit_jump(&mut out, *fail, &format!("{ind}  "), true);
                        out.push_str(&format!("{ind}}}\n"));
                        emit_jump(&mut out, *ok, &ind, false);
                    }
                }
            }
            Terminator::BranchZero {
                on_zero,
                on_nonzero,
            } => {
                let sp_active = sel.is_some_and(is_special);
                let dyn_brz = sel.is_none();
                let val = if sp_active {
                    let var = abs.fresh();
                    out.push_str(&format!("{ind}{var} = sp.pop({});\n", sel.unwrap()));
                    var
                } else if dyn_brz && has_special {
                    let var = abs.fresh();
                    out.push_str(&format!("{ind}if sel == {QUEUE} || sel == {PORT} {{ {var} = sp.pop(sel); }} else {{ top = top.sub(1); {var} = *top; }}\n"));
                    var
                } else if dyn_brz {
                    let var = abs.fresh();
                    out.push_str(&format!("{ind}top = top.sub(1); {var} = *top;\n"));
                    var
                } else {
                    ensure_depth(&mut out, &mut abs, 1, &ind);
                    abs.pop().unwrap()
                };
                if needs_save_back {
                    abs.flush_all(&mut out, &ind);
                    emit_save_back(&mut out, &ind, &used);
                } else {
                    abs.flush_all(&mut out, &ind);
                }
                let zero_is_next = Some(*on_zero) == next_rpo
                    && !scope_closes_before(rpo_pos[on_zero])
                    && !scopes.iter().any(|s| {
                        s.open >= order_idx
                            && s.open < rpo_pos[on_zero]
                            && s.close > rpo_pos[on_zero]
                    });
                if zero_is_next {
                    // Invert: if nonzero { jump }; zero falls through.
                    out.push_str(&format!("{ind}if {val} != 0 {{\n"));
                    emit_jump(&mut out, *on_nonzero, &format!("{ind}  "), true);
                    out.push_str(&format!("{ind}}}\n"));
                } else {
                    out.push_str(&format!("{ind}if {val} == 0 {{\n"));
                    emit_jump(&mut out, *on_zero, &format!("{ind}  "), true);
                    out.push_str(&format!("{ind}}}\n"));
                    emit_jump(&mut out, *on_nonzero, &ind, false);
                }
            }
            Terminator::Halt => {
                if needs_save_back {
                    abs.flush_all(&mut out, &ind);
                    emit_save_back(&mut out, &ind, &used);
                } else {
                    abs.flush_all(&mut out, &ind);
                }
                out.push_str(&format!("{ind}w.flush().ok();\n{ind}let _t = {t}; let _b = {};\n{ind}return if _t > _b {{ *_t.sub(1) }} else {{ 0 }};\n", match sel { Some(s) => format!("bases[{s}]"), None => "bases[sel]".into() }));
            }
        }
        // Don't close guard here — it stays open across consecutive blocks
        // (closed at scope boundaries or goto targets by the top-of-loop logic)
    }

    // Close any remaining open guard
    if goto_guard_open {
        depth -= 1;
        out.push_str(&format!("{}}}\n", indent(depth)));
    }
    while depth > 1 {
        depth -= 1;
        out.push_str(&format!("{}}}\n", indent(depth)));
    }
    out.push_str("  0\n}\n\n");
    let mut var_decl = String::new();
    for i in 0..max_var {
        var_decl.push_str(&format!("  let mut v{i}: i64 = 0;\n"));
    }
    if needs_goto {
        var_decl.push_str("  let mut _goto: usize = 0;\n");
    }
    out = out.replacen("  /*VARDECL*/\n", &var_decl, 1);
    out.push_str(MAIN_FN);
    out
}

const QUEUE: usize = 21;
const PORT: usize = 27;
fn is_special(s: usize) -> bool {
    s == QUEUE || s == PORT
}

/// Common PRELUDE: Int abstraction, SpecialStorage, I/O, dyn_sel helpers.
/// Int impl is provided separately by PRELUDE_INT_I64 or PRELUDE_INT_BIGINT.
const PRELUDE_COMMON: &str = r#"
use std::io::{Read, Write};
use std::collections::VecDeque;
const QUEUE: usize = 21;
const PORT: usize = 27;
const STORAGE_COUNT: usize = 28;
const MAX_STACK: usize = 65536;
struct SpecialStorage { queue: VecDeque<Int>, port: Vec<Int>, port_last: Int }
impl SpecialStorage {
    fn new() -> Self { SpecialStorage { queue: VecDeque::new(), port: Vec::new(), port_last: Int(0) } }
    fn push(&mut self, sel: usize, v: Int) { if sel == QUEUE { self.queue.push_back(v); } else { self.port_last = v; self.port.push(v); } }
    fn pop(&mut self, sel: usize) -> Int { if sel == QUEUE { self.queue.pop_front().unwrap_or(Int(0)) } else { self.port.pop().unwrap_or(Int(0)) } }
    fn depth(&self, sel: usize) -> usize { if sel == QUEUE { self.queue.len() } else { self.port.len() } }
    fn dup(&mut self, sel: usize) { if sel == QUEUE { if let Some(&v) = self.queue.front() { self.queue.push_front(v); } } else { self.port.push(self.port_last); } }
    fn swap(&mut self, sel: usize) { if sel == QUEUE && self.queue.len() >= 2 { let a = self.queue.pop_front().unwrap(); let b = self.queue.pop_front().unwrap(); self.queue.push_front(a); self.queue.push_front(b); } else if sel == PORT && self.port.len() >= 2 { let n = self.port.len(); self.port.swap(n-1, n-2); } }
    fn peek(&self, sel: usize) -> Int { if sel == QUEUE { self.queue.front().copied().unwrap_or(Int(0)) } else { self.port.last().copied().unwrap_or(Int(0)) } }
    fn scan_to_zero(&mut self) -> Int {
        if let Some(pos) = self.queue.iter().position(|v| v.0 == 0) {
            self.queue.rotate_left(pos + 1);
            Int(0)
        } else { Int(0) }
    }
}
#[inline(always)] fn write_i64(w: &mut impl Write, n: i64) { let mut buf = [0u8; 20]; let mut u = if n < 0 { w.write_all(b"-").ok(); (n as u64).wrapping_neg() } else { n as u64 }; let mut i = 20; loop { i -= 1; buf[i] = b'0' + (u % 10) as u8; u /= 10; if u == 0 { break; } } w.write_all(&buf[i..]).ok(); }
#[inline(always)] fn write_char(w: &mut impl Write, v: Int) { let c = int_to_i64(v) as u32; if c <= 0x7F { w.write_all(&[c as u8]).ok(); return; } let mut buf = [0u8; 4]; if let Some(ch) = char::from_u32(c) { let s = ch.encode_utf8(&mut buf); w.write_all(s.as_bytes()).ok(); } }
fn read_num() -> Int { let mut s = String::new(); std::io::stdin().read_line(&mut s).ok(); int_lit(s.trim().parse().unwrap_or(0)) }
fn read_char() -> Int { let mut buf = [0u8; 4]; match std::io::stdin().read(&mut buf[..1]) { Ok(0) | Err(_) => int_lit(-1), Ok(_) => { let b = buf[0]; if b < 0x80 { return int_lit(b as i64); } let (n, mut val) = if b >> 5 == 6 { (1, (b & 0x1F) as i32) } else if b >> 4 == 14 { (2, (b & 0x0F) as i32) } else if b >> 3 == 30 { (3, (b & 0x07) as i32) } else { return int_lit(-1) }; for _ in 0..n { if std::io::stdin().read(&mut buf[..1]).unwrap_or(0) == 0 { return int_lit(-1); } val = (val << 6) | (buf[0] & 0x3F) as i32; } int_lit(val as i64) } } }
#[cold] #[inline(never)] unsafe fn dyn_push_sp(sp: &mut SpecialStorage, sel: usize, v: Int) { sp.push(sel, v); }
#[cold] #[inline(never)] unsafe fn dyn_pop_sp(sp: &mut SpecialStorage, sel: usize) -> Int { sp.pop(sel) }
#[cold] #[inline(never)] unsafe fn dyn_dup_sp(sp: &mut SpecialStorage, sel: usize) { sp.dup(sel); }
#[cold] #[inline(never)] unsafe fn dyn_swap_sp(sp: &mut SpecialStorage, sel: usize) { sp.swap(sel); }
"#;

/// Int = dual-mode: raw i64 → checked → on overflow promote to tagged bigint.
/// `_bm` local variable selects mode (register → ~0 cycle branch).
const PRELUDE_INT_DUAL: &str = r#"use num_traits::ToPrimitive;
const SMALL_MIN: i64 = -(1i64 << 62);
const SMALL_MAX: i64 = (1i64 << 62) - 1;
#[derive(Clone, Copy, PartialEq, Eq)]
#[repr(transparent)]
struct Int(i64);
#[inline(always)] fn promote_val(v: Int) -> Int {
    let r = v.0;
    if r >= SMALL_MIN && r <= SMALL_MAX { Int((r << 1) | 1) }
    else { Int(Box::into_raw(Box::new(BigInt::from(r))) as i64) }
}
fn to_big(v: i64) -> BigInt { if v & 1 != 0 { BigInt::from(v >> 1) } else { unsafe { &*(v as *const BigInt) }.clone() } }
fn normalize(b: BigInt) -> Int { match b.to_i64() { Some(v) if v >= SMALL_MIN && v <= SMALL_MAX => Int((v << 1) | 1), _ => Int(Box::into_raw(Box::new(b)) as i64) } }
#[cold] #[inline(never)] fn big_add(a: Int, b: Int) -> Int { normalize(to_big(a.0) + to_big(b.0)) }
#[cold] #[inline(never)] fn big_sub(a: Int, b: Int) -> Int { normalize(to_big(a.0) - to_big(b.0)) }
#[cold] #[inline(never)] fn big_mul(a: Int, b: Int) -> Int { normalize(to_big(a.0) * to_big(b.0)) }
#[cold] #[inline(never)] fn big_div(a: Int, b: Int) -> Int { normalize(to_big(a.0) / to_big(b.0)) }
#[cold] #[inline(never)] fn big_rem(a: Int, b: Int) -> Int { normalize(to_big(a.0) % to_big(b.0)) }
unsafe fn promote_stacks(bases: &[*mut Int; 28], tops: &[*mut Int; 28]) {
    for s in 0..28 {
        if bases[s].is_null() { continue; }
        let mut p = bases[s];
        while p < tops[s] { *p = promote_val(*p); p = p.add(1); }
    }
}
#[cold] #[inline(never)]
unsafe fn do_promote(bm: &mut bool, bases: &[*mut Int; 28], tops: &mut [*mut Int; 28]) {
    *bm = true; BM = true;
    promote_stacks(bases, tops);
}
#[inline(always)]
unsafe fn dual_add(a: Int, b: Int, bm: &mut bool, bases: &[*mut Int; 28], tops: &mut [*mut Int; 28]) -> Int {
    if !*bm {
        match Int::raw_add(a, b) { Some(r) => r, None => { do_promote(bm, bases, tops); Int::tag_add(promote_val(a), promote_val(b)) } }
    } else { Int::tag_add(a, b) }
}
#[inline(always)]
unsafe fn dual_sub(a: Int, b: Int, bm: &mut bool, bases: &[*mut Int; 28], tops: &mut [*mut Int; 28]) -> Int {
    if !*bm {
        match Int::raw_sub(a, b) { Some(r) => r, None => { do_promote(bm, bases, tops); Int::tag_sub(promote_val(a), promote_val(b)) } }
    } else { Int::tag_sub(a, b) }
}
#[inline(always)]
unsafe fn dual_mul(a: Int, b: Int, bm: &mut bool, bases: &[*mut Int; 28], tops: &mut [*mut Int; 28]) -> Int {
    if !*bm {
        match Int::raw_mul(a, b) { Some(r) => r, None => { do_promote(bm, bases, tops); Int::tag_mul(promote_val(a), promote_val(b)) } }
    } else { Int::tag_mul(a, b) }
}
impl Int {
    // Mode-aware operations: _bm=false → raw i64, _bm=true → tagged
    #[inline(always)] fn lit(v: i64, _bm: bool) -> Int { if _bm { Int((v << 1) | 1) } else { Int(v) } }
    #[inline(always)] fn to_i64(v: Int, _bm: bool) -> i64 { if _bm { if v.0 & 1 != 0 { v.0 >> 1 } else { unsafe { &*(v.0 as *const BigInt) }.to_i64().unwrap_or(0) } } else { v.0 } }
}
// Static flag for free functions (PRELUDE_COMMON) to detect mode
static mut BM: bool = false;
#[inline(always)] fn int_lit(v: i64) -> Int { if unsafe { BM } { Int((v << 1) | 1) } else { Int(v) } }
#[inline(always)] fn int_to_i64(v: Int) -> i64 { if unsafe { BM } { if v.0 & 1 != 0 { v.0 >> 1 } else { unsafe { &*(v.0 as *const BigInt) }.to_i64().unwrap_or(0) } } else { v.0 } }
impl Int {
    #[inline(always)] fn is_zero(v: Int, _bm: bool) -> bool { if _bm { v.0 == 1 } else { v.0 == 0 } }
    #[inline(always)] fn ge(a: Int, b: Int, _bm: bool) -> bool { if _bm { if a.0 & b.0 & 1 != 0 { a.0 >= b.0 } else { to_big(a.0) >= to_big(b.0) } } else { a.0 >= b.0 } }
    // Fast-path add/sub: raw checked arithmetic. Overflow handled by caller.
    #[inline(always)] fn raw_add(a: Int, b: Int) -> Option<Int> { a.0.checked_add(b.0).map(Int) }
    #[inline(always)] fn raw_sub(a: Int, b: Int) -> Option<Int> { a.0.checked_sub(b.0).map(Int) }
    #[inline(always)] fn raw_mul(a: Int, b: Int) -> Option<Int> { a.0.checked_mul(b.0).map(Int) }
    // Tagged-path operations (after promotion)
    #[inline(always)] fn tag_add(a: Int, b: Int) -> Int {
        if a.0 & b.0 & 1 != 0 { if let Some(r) = a.0.checked_add(b.0 - 1) { return Int(r); } }
        big_add(a, b)
    }
    #[inline(always)] fn tag_sub(a: Int, b: Int) -> Int {
        if a.0 & b.0 & 1 != 0 { if let Some(r) = a.0.checked_sub(b.0 - 1) { return Int(r); } }
        big_sub(a, b)
    }
    #[inline(always)] fn tag_mul(a: Int, b: Int) -> Int {
        if a.0 & b.0 & 1 != 0 { let av = a.0 >> 1; let bv = b.0 >> 1;
            if let Some(r) = av.checked_mul(bv) { if r >= SMALL_MIN && r <= SMALL_MAX { return Int((r << 1) | 1); } } }
        big_mul(a, b)
    }
    #[inline(always)] fn div(a: Int, b: Int, _bm: bool) -> Int {
        if _bm { if b.0 == 1 { return Int(1); } if a.0 & b.0 & 1 != 0 { return Int(((a.0>>1).wrapping_div(b.0>>1)<<1)|1); } big_div(a, b) }
        else { Int(if b.0 != 0 { a.0.wrapping_div(b.0) } else { 0 }) }
    }
    #[inline(always)] fn rem(a: Int, b: Int, _bm: bool) -> Int {
        if _bm { if b.0 == 1 { return Int(1); } if a.0 & b.0 & 1 != 0 { return Int(((a.0>>1).wrapping_rem(b.0>>1)<<1)|1); } big_rem(a, b) }
        else { Int(if b.0 != 0 { a.0.wrapping_rem(b.0) } else { 0 }) }
    }
}
fn write_num(w: &mut impl std::io::Write, v: Int) { if !unsafe { BM } { write_i64(w, v.0); } else if v.0 & 1 != 0 { write_i64(w, v.0 >> 1); } else { use std::io::Write as _; write!(w, "{}", unsafe { &*(v.0 as *const BigInt) }).ok(); } }
"#;

/// Int = i64 (wrapping arithmetic, no bigint). Zero overhead.
const PRELUDE_INT_I64: &str = r#"#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
#[repr(transparent)]
struct Int(i64);
impl Int {
    const ZERO: Int = Int(0);
    const ONE: Int = Int(1);
    #[inline(always)] fn lit(v: i64) -> Int { Int(v) }
}
#[inline(always)] fn int_lit(v: i64) -> Int { Int(v) }
#[inline(always)] fn int_to_i64(v: Int) -> i64 { v.0 }
impl Int {
    #[inline(always)] fn is_zero(v: Int) -> bool { v.0 == 0 }
    #[inline(always)] fn ge(a: Int, b: Int) -> bool { a.0 >= b.0 }
    #[inline(always)] fn add(a: Int, b: Int) -> Int { Int(a.0.wrapping_add(b.0)) }
    #[inline(always)] fn sub(a: Int, b: Int) -> Int { Int(a.0.wrapping_sub(b.0)) }
    #[inline(always)] fn mul(a: Int, b: Int) -> Int { Int(a.0.wrapping_mul(b.0)) }
    #[inline(always)] fn div(a: Int, b: Int) -> Int { Int(if b.0 != 0 { a.0.wrapping_div(b.0) } else { 0 }) }
    #[inline(always)] fn rem(a: Int, b: Int) -> Int { Int(if b.0 != 0 { a.0.wrapping_rem(b.0) } else { 0 }) }
}
#[inline(always)] fn write_num(w: &mut impl std::io::Write, v: Int) { write_i64(w, v.0); }
"#;

/// Complete bigint prelude: Val type + SpecialStorage + I/O + val_* operations.
/// Int = tagged i64: small=(v<<1)|1, big=heap BigInt*.
/// Fast path: i64 bit tricks. Slow path: BigInt via malachite.
const PRELUDE_INT_BIGINT: &str = r#"use num_traits::ToPrimitive;
const SMALL_MIN: i64 = -(1i64 << 62);
const SMALL_MAX: i64 = (1i64 << 62) - 1;
fn normalize(b: BigInt) -> Int { match b.to_i64() { Some(v) if v >= SMALL_MIN && v <= SMALL_MAX => Int((v << 1) | 1), _ => Int(Box::into_raw(Box::new(b)) as i64) } }
fn to_big(v: i64) -> BigInt { if v & 1 != 0 { BigInt::from(v >> 1) } else { unsafe { &*(v as *const BigInt) }.clone() } }
#[cold] #[inline(never)] fn big_add(a: Int, b: Int) -> Int { normalize(to_big(a.0) + to_big(b.0)) }
#[cold] #[inline(never)] fn big_sub(a: Int, b: Int) -> Int { normalize(to_big(a.0) - to_big(b.0)) }
#[cold] #[inline(never)] fn big_mul(a: Int, b: Int) -> Int { normalize(to_big(a.0) * to_big(b.0)) }
#[cold] #[inline(never)] fn big_div(a: Int, b: Int) -> Int { normalize(to_big(a.0) / to_big(b.0)) }
#[cold] #[inline(never)] fn big_rem(a: Int, b: Int) -> Int { normalize(to_big(a.0) % to_big(b.0)) }
#[derive(Clone, Copy, PartialEq, Eq)]
#[repr(transparent)]
struct Int(i64);
#[inline(always)] fn int_lit(v: i64) -> Int { Int((v << 1) | 1) }
#[inline(always)] fn int_to_i64(v: Int) -> i64 { if v.0 & 1 != 0 { v.0 >> 1 } else { unsafe { &*(v.0 as *const BigInt) }.to_i64().unwrap_or(0) } }
impl Int {
    const ZERO: Int = Int(1);   // (0 << 1) | 1
    const ONE: Int = Int(3);    // (1 << 1) | 1
    #[inline(always)] fn lit(v: i64) -> Int { Int((v << 1) | 1) }
    #[inline(always)] fn to_i64(v: Int) -> i64 { if v.0 & 1 != 0 { v.0 >> 1 } else { unsafe { &*(v.0 as *const BigInt) }.to_i64().unwrap_or(0) } }
    #[inline(always)] fn is_zero(v: Int) -> bool { v.0 == 1 }
    #[inline(always)] fn ge(a: Int, b: Int) -> bool { if a.0 & b.0 & 1 != 0 { a.0 >= b.0 } else { to_big(a.0) >= to_big(b.0) } }
    #[inline(always)] fn add(a: Int, b: Int) -> Int {
        if a.0 & b.0 & 1 != 0 { if let Some(r) = a.0.checked_add(b.0 - 1) { return Int(r); } }
        big_add(a, b)
    }
    #[inline(always)] fn sub(a: Int, b: Int) -> Int {
        if a.0 & b.0 & 1 != 0 { if let Some(r) = a.0.checked_sub(b.0 - 1) { return Int(r); } }
        big_sub(a, b)
    }
    #[inline(always)] fn mul(a: Int, b: Int) -> Int {
        if a.0 & b.0 & 1 != 0 { let av = a.0 >> 1; let bv = b.0 >> 1;
            if let Some(r) = av.checked_mul(bv) { if r >= SMALL_MIN && r <= SMALL_MAX { return Int((r << 1) | 1); } } }
        big_mul(a, b)
    }
    #[inline(always)] fn div(a: Int, b: Int) -> Int {
        if b.0 == 1 { return Int(1); }
        if a.0 & b.0 & 1 != 0 { return Int(((a.0 >> 1).wrapping_div(b.0 >> 1) << 1) | 1); }
        big_div(a, b)
    }
    #[inline(always)] fn rem(a: Int, b: Int) -> Int {
        if b.0 == 1 { return Int(1); }
        if a.0 & b.0 & 1 != 0 { return Int(((a.0 >> 1).wrapping_rem(b.0 >> 1) << 1) | 1); }
        big_rem(a, b)
    }
}
fn write_num(w: &mut impl std::io::Write, v: Int) { if v.0 & 1 != 0 { write_i64(w, v.0 >> 1); } else { use std::io::Write as _; write!(w, "{}", unsafe { &*(v.0 as *const BigInt) }).ok(); } }
"#;

const MAIN_FN: &str = r#"
fn main() {
    let mut data: Vec<Vec<Int>> = (0..STORAGE_COUNT).map(|_| vec![Int(0); MAX_STACK]).collect();
    let mut bases: [*mut Int; 28] = { let mut b = [std::ptr::null_mut(); 28]; for i in 0..28 { b[i] = data[i].as_mut_ptr(); } b };
    let mut lengths = [0i32; 28];
    let stdout = std::io::stdout();
    let mut w = std::io::BufWriter::with_capacity(16384, stdout.lock());
    let result = unsafe { aheui_main(&mut bases, &mut lengths, &mut w) };
    w.flush().ok();
    std::process::exit(int_to_i64(result) as i32);
}
"#;

/// Dual-mode main: result may be raw or tagged. to_i64 handles both.
const MAIN_FN_DUAL: &str = r#"
fn main() {
    let mut data: Vec<Vec<Int>> = (0..STORAGE_COUNT).map(|_| vec![Int(0); MAX_STACK]).collect();
    let mut bases: [*mut Int; 28] = { let mut b = [std::ptr::null_mut(); 28]; for i in 0..28 { b[i] = data[i].as_mut_ptr(); } b };
    let mut lengths = [0i32; 28];
    let stdout = std::io::stdout();
    let mut w = std::io::BufWriter::with_capacity(16384, stdout.lock());
    let result = unsafe { aheui_main(&mut bases, &mut lengths, &mut w) };
    w.flush().ok();
    std::process::exit(int_to_i64(result) as i32);
}
"#;
